import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { db, id } from "../../lib/db";
import { useCurrent } from "../../lib/auth/CurrentUserContext";
import { statusLabel } from "../../lib/locations";
import { attachmentLink, type AttachmentTarget } from "../../lib/attachments";
import { AttachmentTargetPicker } from "../shared/AttachmentTargetPicker";
import { PRIORITY_ORDER } from "../../lib/workItems";

// Navigation state accepted from callers opening this form in context —
// e.g. Location Detail pre-attaching its own location, or Incident Detail
// raising a linked ticket (sourceIncidentId is never user-editable).
export interface NewTicketState {
  target?: AttachmentTarget;
  sourceIncidentId?: string;
  title?: string;
  description?: string;
}

// Tickets — New Ticket Form (see pages/new-ticket-form.html).
// Unrestricted by design; always created unassigned, status Open.
export function NewTicketPage() {
  const current = useCurrent();
  const navigate = useNavigate();
  const state = (useLocation().state ?? {}) as NewTicketState;

  const [title, setTitle] = useState(state.title ?? "");
  const [description, setDescription] = useState(state.description ?? "");
  const [priority, setPriority] = useState("medium");
  const [target, setTarget] = useState<AttachmentTarget | null>(state.target ?? null);
  const [targetLocked, setTargetLocked] = useState(Boolean(state.target));
  const [saving, setSaving] = useState(false);

  const submit = async () => {
    if (!title.trim() || !target) return;
    setSaving(true);
    const ticketId = id();
    await db.transact(
      db.tx.tickets[ticketId]
        .update({
          title: title.trim(),
          description: description.trim() || undefined,
          priority,
          status: "open",
          autoGenerated: false,
          createdAt: Date.now(),
        })
        .link({
          ...attachmentLink(target),
          ...(current.user ? { createdBy: current.user.id } : {}),
          ...(state.sourceIncidentId ? { sourceIncident: state.sourceIncidentId } : {}),
        }),
    );
    navigate(`/tickets/${ticketId}`, { replace: true });
  };

  return (
    <div style={{ maxWidth: 560 }}>
      <div className="page-head">
        <h1 className="page-title">New Ticket</h1>
      </div>

      <div className="field">
        <span className="field-label">Title — required</span>
        <input
          className="input"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          autoFocus
        />
      </div>

      <div className="field">
        <span className="field-label">Description (markdown, optional)</span>
        <textarea
          className="textarea"
          rows={5}
          value={description}
          onChange={(e) => setDescription(e.target.value)}
        />
      </div>

      <div className="field">
        <span className="field-label">Priority</span>
        <select
          className="select select-inline"
          value={priority}
          onChange={(e) => setPriority(e.target.value)}
        >
          {PRIORITY_ORDER.map((p) => (
            <option key={p} value={p}>
              {statusLabel(p)}
            </option>
          ))}
        </select>
      </div>

      <div className="field">
        <span className="field-label">Attachment target — required</span>
        {targetLocked && target ? (
          <div className="field-value">
            {target.label}{" "}
            <button
              type="button"
              className="btn btn-sm btn-quiet"
              onClick={() => {
                setTarget(null);
                setTargetLocked(false);
              }}
            >
              Change
            </button>
          </div>
        ) : (
          <AttachmentTargetPicker value={target} onChange={setTarget} />
        )}
      </div>

      <div className="row" style={{ marginTop: 16 }}>
        <button
          type="button"
          className="btn btn-primary"
          disabled={!title.trim() || !target || saving}
          onClick={() => void submit()}
        >
          Create Ticket
        </button>
        <button type="button" className="btn btn-quiet" onClick={() => navigate(-1)}>
          Cancel
        </button>
      </div>
    </div>
  );
}
