import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useCurrent } from "../../lib/auth/CurrentUserContext";
import { statusLabel } from "../../lib/locations";
import { attachmentOf, targetPath } from "../../data/attachments";
import { NoteDialog } from "../shared/NoteDialog";
import { PRIORITY_ORDER, priorityBadgeClass } from "../../lib/workItems";
import {
  assignTicket,
  setTicketPriority,
  setTicketStatus,
  useTicket,
} from "../../data/tickets";
import { useTicketStatuses } from "../../data/lookups";
import { useUsers } from "../../data/users";

// Tickets — Ticket Detail (see pages/ticket-detail.html).
// Status/priority edits are unrestricted; only assignment is gated. A ticket
// with a source incident shows no trace of it without view_incidents.

export function TicketDetailPage() {
  const { id: ticketId } = useParams();
  const current = useCurrent();
  const [showNoteDialog, setShowNoteDialog] = useState(false);

  const { ticket } = useTicket(ticketId);
  const { data: users } = useUsers();
  // The status list is the marina's own, so a marina that added "Waiting on
  // parts" gets it here without a code change. The ticket's current status is
  // always included even if it was since retired, or a ticket would silently
  // change status by being looked at.
  const { statuses } = useTicketStatuses();

  if (!ticket) {
    return (
      <div className="placeholder">
        <div className="big">Loading…</div>
      </div>
    );
  }

  const target = attachmentOf(ticket);
  const actorId = current.user?.id ?? null;

  const setStatus = (statusId: string) => {
    const status = statuses.find((s) => s.id === statusId);
    if (status) void setTicketStatus(ticket, status, actorId);
  };
  const setPriority = (priority: string) => {
    void setTicketPriority(ticket, priority, statusLabel(priority), actorId);
  };
  const assign = (userId: string) => {
    if (!userId) return;
    const assignee = users.find((u) => u.id === userId);
    void assignTicket(
      ticket,
      { id: userId, name: assignee?.name ?? "someone" },
      actorId,
    );
  };

  return (
    <div>
      <div className="page-head">
        <div>
          <h1 className="page-title">{ticket.title}</h1>
          <div className="page-sub">
            Created by {ticket.creator_name ?? "—"} ·{" "}
            {new Date(ticket.created_at).toLocaleString(undefined, {
              month: "short",
              day: "numeric",
              hour: "numeric",
              minute: "2-digit",
            })}
            {ticket.auto_generated === 1 &&
              " · auto-generated by a maintenance rule"}
          </div>
        </div>
        <button type="button" className="btn btn-sm" onClick={() => setShowNoteDialog(true)} disabled={!target}>
          + Note
        </button>
      </div>

      <div className="grid-2">
        <div>
          <div className="field">
            <span className="field-label">Priority</span>
            <select
              className="select select-inline"
              value={ticket.priority}
              onChange={(e) => setPriority(e.target.value)}
            >
              {PRIORITY_ORDER.map((p) => (
                <option key={p} value={p}>
                  {statusLabel(p)}
                </option>
              ))}
            </select>{" "}
            <span className={priorityBadgeClass(ticket.priority)}>
              {statusLabel(ticket.priority)}
            </span>
          </div>

          <div className="field">
            <span className="field-label">Status</span>
            <select
              className="select select-inline"
              value={ticket.status_id}
              onChange={(e) => setStatus(e.target.value)}
            >
              {statuses.some((s) => s.id === ticket.status_id) || (
                <option value={ticket.status_id}>{ticket.status_name}</option>
              )}
              {statuses.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
            {ticket.resolved_at && (
              <span className="muted small">
                {" "}
                resolved {new Date(ticket.resolved_at).toLocaleDateString()}
              </span>
            )}
          </div>

          <div className="field">
            <span className="field-label">Assigned to</span>
            <div className="field-value row">
              <span>
                {ticket.assignee_name ?? (
                  <span className="muted">Unassigned</span>
                )}
              </span>
              {!ticket.assigned_to_id && current.can("assign_ticket_to_self") && (
                <button
                  type="button"
                  className="btn btn-sm"
                  onClick={() => current.user && assign(current.user.id)}
                >
                  Take
                </button>
              )}
              {current.can("assign_ticket_to_others") && (
                <select
                  className="select select-inline"
                  value=""
                  onChange={(e) => assign(e.target.value)}
                >
                  <option value="">Assign…</option>
                  {users.map((u) => (
                    <option key={u.id} value={u.id}>
                      {u.name}
                    </option>
                  ))}
                </select>
              )}
            </div>
          </div>

          {target && (
            <div className="field">
              <span className="field-label">Attached to</span>
              <div className="field-value">
                <Link to={targetPath(target)}>{target.label}</Link>
              </div>
            </div>
          )}

          {ticket.source_incident_id && current.can("view_incidents") && (
            <div className="field">
              <span className="field-label">Source incident</span>
              <div className="field-value">
                <Link to={`/incidents/${ticket.source_incident_id}`}>
                  {/* The incident itself may be outside this device's sync
                      window even when the ticket is not, so its title can be
                      absent while the link still works online. */}
                  {ticket.source_incident_title ?? "Incident"}
                </Link>
              </div>
            </div>
          )}
        </div>

        <div>
          {ticket.description ? (
            <div className="card">
              {/* Markdown source shown as plain text until a renderer lands. */}
              <div className="small" style={{ whiteSpace: "pre-wrap" }}>
                {ticket.description}
              </div>
            </div>
          ) : (
            <div className="placeholder">
              <div className="big">No description</div>
            </div>
          )}
        </div>
      </div>

      {showNoteDialog && target && (
        <NoteDialog target={target} onClose={() => setShowNoteDialog(false)} />
      )}
    </div>
  );
}
