import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { db } from "../../lib/db";
import { useCurrent } from "../../lib/auth/CurrentUserContext";
import { statusLabel } from "../../lib/locations";
import {
  ATTACHMENT_LINKS_QUERY,
  attachmentOf,
  targetPath,
} from "../../lib/attachments";
import { NoteDialog } from "../shared/NoteDialog";
import { PRIORITY_ORDER, priorityBadgeClass } from "../../lib/workItems";
import { activityTx } from "../../lib/activityLog";

// Tickets — Ticket Detail (see pages/ticket-detail.html).
// Status/priority edits are unrestricted; only assignment is gated. A ticket
// with a source incident shows no trace of it without view_incidents.
const TICKET_STATUSES = ["open", "assigned", "in_progress", "complete"] as const;

export function TicketDetailPage() {
  const { id: ticketId } = useParams();
  const current = useCurrent();
  const [showNoteDialog, setShowNoteDialog] = useState(false);

  const { data } = db.useQuery(
    ticketId
      ? {
          tickets: {
            $: { where: { id: ticketId } },
            assignedTo: {},
            createdBy: {},
            sourceIncident: {},
            sourceChecklistItem: {},
            ...ATTACHMENT_LINKS_QUERY,
          },
          users: { $: { where: { active: true } } },
        }
      : null,
  );
  const ticket = data?.tickets?.[0];
  const users = data?.users ?? [];

  if (!ticket) {
    return (
      <div className="placeholder">
        <div className="big">Loading…</div>
      </div>
    );
  }

  const target = attachmentOf(ticket);

  const logTicket = (eventType: string, summary: string) =>
    activityTx({
      eventType,
      summary,
      subjectType: "tickets",
      subjectId: ticket.id,
      actorId: current.user?.id,
    });

  const setStatus = (status: string) => {
    // resolvedAt tracks the terminal status; cleared if the ticket reopens.
    void db.transact([
      db.tx.tickets[ticket.id].update({
        status,
        resolvedAt: status === "complete" ? Date.now() : null,
      }),
      logTicket(
        "ticket.status_changed",
        `"${ticket.title}" set to ${statusLabel(status)}`,
      ),
    ]);
  };
  const setPriority = (priority: string) => {
    void db.transact([
      db.tx.tickets[ticket.id].update({ priority }),
      logTicket(
        "ticket.priority_changed",
        `"${ticket.title}" priority set to ${statusLabel(priority)}`,
      ),
    ]);
  };
  const assign = (userId: string) => {
    if (!userId) return;
    const assignee = users.find((u) => u.id === userId);
    void db.transact([
      db.tx.tickets[ticket.id].link({ assignedTo: userId }),
      logTicket(
        "ticket.assigned",
        `"${ticket.title}" assigned to ${assignee?.name ?? "someone"}`,
      ),
    ]);
  };

  return (
    <div>
      <div className="page-head">
        <div>
          <h1 className="page-title">{ticket.title}</h1>
          <div className="page-sub">
            Created by {ticket.createdBy?.name ?? "—"} ·{" "}
            {new Date(ticket.createdAt).toLocaleString(undefined, {
              month: "short",
              day: "numeric",
              hour: "numeric",
              minute: "2-digit",
            })}
            {ticket.autoGenerated && " · auto-generated by a maintenance rule"}
          </div>
        </div>
        <button type="button" className="btn btn-sm" onClick={() => setShowNoteDialog(true)} disabled={!target}>
          + Note
        </button>
      </div>

      <div className="grid-2">
        <div>
          <div className="field">
            <span className="field-label">Priority</span>
            <select
              className="select select-inline"
              value={ticket.priority}
              onChange={(e) => setPriority(e.target.value)}
            >
              {PRIORITY_ORDER.map((p) => (
                <option key={p} value={p}>
                  {statusLabel(p)}
                </option>
              ))}
            </select>{" "}
            <span className={priorityBadgeClass(ticket.priority)}>
              {statusLabel(ticket.priority)}
            </span>
          </div>

          <div className="field">
            <span className="field-label">Status</span>
            <select
              className="select select-inline"
              value={ticket.status}
              onChange={(e) => setStatus(e.target.value)}
            >
              {[...new Set([...TICKET_STATUSES, ticket.status])].map((s) => (
                <option key={s} value={s}>
                  {statusLabel(s)}
                </option>
              ))}
            </select>
            {ticket.resolvedAt && (
              <span className="muted small">
                {" "}
                resolved {new Date(ticket.resolvedAt).toLocaleDateString()}
              </span>
            )}
          </div>

          <div className="field">
            <span className="field-label">Assigned to</span>
            <div className="field-value row">
              <span>{ticket.assignedTo?.name ?? <span className="muted">Unassigned</span>}</span>
              {!ticket.assignedTo && current.can("assign_ticket_to_self") && (
                <button
                  type="button"
                  className="btn btn-sm"
                  onClick={() => current.user && assign(current.user.id)}
                >
                  Take
                </button>
              )}
              {current.can("assign_ticket_to_others") && (
                <select
                  className="select select-inline"
                  value=""
                  onChange={(e) => assign(e.target.value)}
                >
                  <option value="">Assign…</option>
                  {users.map((u) => (
                    <option key={u.id} value={u.id}>
                      {u.name}
                    </option>
                  ))}
                </select>
              )}
            </div>
          </div>

          {target && (
            <div className="field">
              <span className="field-label">Attached to</span>
              <div className="field-value">
                <Link to={targetPath(target)}>{target.label}</Link>
              </div>
            </div>
          )}

          {ticket.sourceIncident && current.can("view_incidents") && (
            <div className="field">
              <span className="field-label">Source incident</span>
              <div className="field-value">
                <Link to={`/incidents/${ticket.sourceIncident.id}`}>
                  {ticket.sourceIncident.title}
                </Link>
              </div>
            </div>
          )}
        </div>

        <div>
          {ticket.description ? (
            <div className="card">
              {/* Markdown source shown as plain text until a renderer lands. */}
              <div className="small" style={{ whiteSpace: "pre-wrap" }}>
                {ticket.description}
              </div>
            </div>
          ) : (
            <div className="placeholder">
              <div className="big">No description</div>
            </div>
          )}
        </div>
      </div>

      {showNoteDialog && target && (
        <NoteDialog target={target} onClose={() => setShowNoteDialog(false)} />
      )}
    </div>
  );
}
