import { db, id, type AppSchema } from "./db";
import { activityTx } from "./activityLog";
import { dueMeterMaintenanceRules, maintenanceRuleTitle } from "./maintenanceRules";
import type { TransactionChunk } from "@instantdb/react";
import type {
  ItemResult,
  PendingIncident,
  PendingMeterReading,
  PendingTicket,
} from "./checklists";

type TxChunk = TransactionChunk<AppSchema, keyof AppSchema["entities"]>;

/**
 * Turns the side effects an item *described* while the guard worked into the
 * rows they represent, at submit time (see docs/pages/active-checklist.html).
 *
 * Nothing here runs until the checklist is submitted, which is what makes a
 * completed item editable: redoing an item only rewrites its own result row,
 * because no Incident, Ticket, meter reading or Asset mutation exists yet to
 * unwind.
 */

interface Collected {
  incidents: PendingIncident[];
  tickets: PendingTicket[];
  readings: PendingMeterReading[];
  /** result-row id → ticket id, so linked_ticket can be attached at submit. */
  ticketByResultId: Map<string, string>;
}

export function collectPendingEffects(
  rows: { id: string; result?: unknown }[],
): Collected {
  const out: Collected = {
    incidents: [],
    tickets: [],
    readings: [],
    ticketByResultId: new Map(),
  };
  for (const row of rows) {
    const r = row.result as ItemResult | undefined;
    if (!r) continue;
    if (r.type === "door_check" || r.type === "gas_pump_check") {
      if (r.pendingIncident) out.incidents.push(r.pendingIncident);
      if (r.pendingTicket) {
        out.tickets.push(r.pendingTicket);
        out.ticketByResultId.set(row.id, r.pendingTicket.id);
      }
    } else if (r.type === "verify_task") {
      if (r.pendingTicket) {
        out.tickets.push(r.pendingTicket);
        out.ticketByResultId.set(row.id, r.pendingTicket.id);
      }
    } else if (r.type === "meter_reading") {
      if (r.pendingReading) out.readings.push(r.pendingReading);
    }
  }
  return out;
}

/**
 * Builds every transaction chunk a submit needs for its deferred effects.
 * Maintenance rules are evaluated here rather than when the reading was
 * typed, so they judge the number actually submitted; that needs a read, so
 * this is async and must be awaited before the submit transaction is sent.
 */
export async function buildPendingEffectTxns(
  collected: Collected,
  actorId: string | undefined,
) {
  // Chunks target several namespaces, so widen to the schema's union.
  const txns: TxChunk[] = [];

  for (const incident of collected.incidents) {
    txns.push(
      db.tx.incidents[incident.id]
        .update({
          title: incident.title,
          status: "open",
          details: incident.details || undefined,
          // The moment the guard found it, not the moment they submitted.
          createdAt: incident.openedAt,
        })
        .link({
          ...(incident.target ? { [incident.target.type]: incident.target.id } : {}),
          ...(actorId ? { author: actorId } : {}),
        }),
    );
    txns.push(
      activityTx({
        eventType: "incident.created",
        summary: incident.title,
        subjectType: "incidents",
        subjectId: incident.id,
        actorId,
      }),
    );
  }

  for (const ticket of collected.tickets) {
    txns.push(
      db.tx.tickets[ticket.id]
        .update({
          title: ticket.title,
          description: ticket.description || undefined,
          priority: ticket.priority,
          status: "open",
          autoGenerated: ticket.autoGenerated,
          createdAt: ticket.openedAt,
        })
        .link({
          ...(ticket.sourceIncidentId ? { sourceIncident: ticket.sourceIncidentId } : {}),
          ...(ticket.assetId ? { asset: ticket.assetId } : {}),
        }),
    );
  }

  for (const reading of collected.readings) {
    txns.push(
      db.tx.assetMeterReadings[reading.id]
        .update({
          value: reading.value,
          source: "checklist_item",
          timestamp: reading.openedAt,
          ...(reading.correctionReason ? { correctionReason: reading.correctionReason } : {}),
        })
        .link({ asset: reading.assetId }),
      db.tx.assets[reading.assetId].update({
        meterReading: reading.value,
      }),
    );

    // Maintenance rules are checked against live history plus this reading,
    // so a rule already ticketed by someone else doesn't get a duplicate.
    const { data: fresh } = await db.queryOnce({
      assets: { $: { where: { id: reading.assetId } } },
      assetMeterReadings: { $: { where: { "asset.id": reading.assetId } } },
      tickets: { $: { where: { "asset.id": reading.assetId } } },
    });
    const asset = fresh?.assets?.[0];
    if (!asset) continue;
    for (const rule of dueMeterMaintenanceRules(
      asset,
      reading.value,
      fresh?.assetMeterReadings ?? [],
      fresh?.tickets ?? [],
    )) {
      txns.push(
        db.tx.tickets[id()]
          .update({
            title: maintenanceRuleTitle(asset, rule),
            priority: "medium",
            status: "open",
            autoGenerated: true,
            createdAt: reading.openedAt,
          })
          .link({ asset: reading.assetId }),
      );
    }
  }

  return txns;
}
