// Checklists & Tours — shared shapes for the opaque json fields on
// ChecklistTemplateItem.config / ChecklistItemResult.result / Checklist.triggeredBy
// (see instant.schema.ts — these are typed here rather than in the schema
// itself since InstantDB's json columns are untyped storage).
import type { InstaQLEntity } from "@instantdb/react";
import type { AppSchema } from "./db";

export type ItemType =
  | "simple_check"
  | "verify_task"
  | "door_check"
  | "lock_check"
  | "location_check"
  | "meter_reading";

/**
 * Item types that record a physical thing's state as found and as left.
 * A Lock Check is the same check as a door with a shorter vocabulary — a
 * padlocked gate, a fuel pump, a shed hasp has no "open" state, only locked
 * or unlocked — so the two share one implementation parameterised by the
 * states they allow.
 */
export type StateCheckType = "door_check" | "lock_check";

/**
 * Lock Check shipped briefly as "gas_pump_check" before it was generalised
 * past fuel pumps. Rows written in that window keep the old string, so it's
 * mapped rather than migrated — the type is opaque storage, and a rename
 * shouldn't strand anyone's template.
 */
const LEGACY_ITEM_TYPES: Record<string, ItemType> = {
  gas_pump_check: "lock_check",
};

export function normalizeItemType(type: string): string {
  return LEGACY_ITEM_TYPES[type] ?? type;
}

export const STATE_CHECK_KINDS: Record<
  StateCheckType,
  { label: string; noun: string; states: DoorState[]; defaultState: DoorState }
> = {
  door_check: {
    label: "Door Check",
    noun: "door",
    states: ["open", "unlocked", "locked"],
    defaultState: "locked",
  },
  lock_check: {
    label: "Lock Check",
    noun: "lock",
    states: ["unlocked", "locked"],
    defaultState: "locked",
  },
};

export function isStateCheck(type: string): type is StateCheckType {
  const t = normalizeItemType(type);
  return t === "door_check" || t === "lock_check";
}

// "Closed" isn't its own state — a door that's locked or unlocked is
// necessarily closed, so those two states already imply it.
export type DoorState = "open" | "unlocked" | "locked";

// ---- ChecklistTemplateItem.config, per type ----

export interface VerifyTaskConfig {
  requireAttemptBeforeReject?: boolean;
}
export interface DoorCheckConfig {
  /** The expected state — of the final/left state only when finalStateOnly is set. */
  expectedState: DoorState;
  /**
   * The Location this door or pump belongs to — required, and what a mismatch
   * incident attaches to. A door isn't an entity of its own (it's a labelled
   * item on a template), so without this there is nothing to attach to.
   * Defaulted from the template's checkpoint when the item is created, and
   * flagged in the template builder when missing. Still optional in the type
   * because items authored before it existed have none.
   */
  locationId?: string;
  /**
   * Some doors/locks have no legitimate "should already be" state — e.g. one
   * that's meant to be unlocked during the day and locked overnight has no
   * single expected state a guard could be checking it against on arrival.
   * When set, the guard is only asked what state they're leaving it in; there
   * is no "found" question and therefore no found-state incident.
   */
  finalStateOnly?: boolean;
}
export interface LocationCheckConfig {
  locationId: string;
  templateId: string;
}
export interface MeterReadingConfig {
  /** Fixed by the template; absent means the guard selects an asset at runtime. */
  assetId?: string;
}

// ---- Deferred side effects ----

/**
 * Incidents, tickets and meter readings raised by a checklist item are
 * *described* while the guard works and only *written* when the checklist is
 * submitted. Until then an item can be edited or redone freely, which would
 * otherwise mean deleting real Incidents and Tickets, un-bumping an Asset's
 * meter, and retracting auto-generated maintenance work — none of which the
 * app can do safely.
 *
 * `openedAt` is captured when the guard actually recorded the finding, not
 * when submit happens, so a door found open at 02:10 and submitted at 05:45
 * reports as having been found open at 02:10.
 *
 * The ids are minted up front so a result can reference its own effects
 * before those rows exist, and so re-submitting can't duplicate them.
 */
export interface PendingIncident {
  id: string;
  title: string;
  details?: string;
  openedAt: number;
  /** Attachment target; absent means the item had no location bound. */
  target?: { type: string; id: string; label: string };
}
export interface PendingTicket {
  id: string;
  title: string;
  description?: string;
  openedAt: number;
  priority: string;
  autoGenerated: boolean;
  /** Links the ticket back to the incident raised by the same item. */
  sourceIncidentId?: string;
  assetId?: string;
}
export interface PendingMeterReading {
  id: string;
  assetId: string;
  value: number;
  openedAt: number;
  correctionReason?: string;
}

// ---- ChecklistItemResult.result, per type ----

export interface SimpleCheckResult {
  type: "simple_check";
  completedAt: number;
}
export interface VerifyTaskResult {
  type: "verify_task";
  outcome: "confirmed" | "rejected_reason" | "rejected_ticket";
  reason?: string;
  attempted?: boolean;
  pendingTicket?: PendingTicket;
}
export interface DoorCheckAttempt {
  observed: DoorState;
  matched: boolean;
}
/**
 * Records the door's state *as found* and *as left*, separately — the whole
 * point of a door check for reporting. "Locked when I left" says nothing
 * about whether it was standing open when the guard walked up, and only the
 * pair together answers both "was this door secure overnight?" and "did the
 * guard fix it?".
 *
 * initialState/finalState are optional only because rows written before this
 * change carry the older attempts/resolution shape instead. Read either via
 * doorCheckSummary() rather than branching on shape at each call site.
 */
export interface DoorCheckResult {
  type: StateCheckType;
  expected: DoorState;
  initialState?: DoorState;
  finalState?: DoorState;
  note?: string;
  /** Incident raised because the door was found in the wrong state. */
  pendingIncident?: PendingIncident;
  /** Raised when the door was left in a state that still isn't expected. */
  pendingTicket?: PendingTicket;
  /** Set once the deferred effects were actually written, at submit. */
  incidentId?: string;
  /** @deprecated pre-initial/final shape; still present on historical rows. */
  attempts?: DoorCheckAttempt[];
  /** @deprecated pre-initial/final shape; still present on historical rows. */
  resolution?: "matched" | "note" | "ticket";
}
export interface LocationCheckResult {
  type: "location_check";
  nestedChecklistId: string;
}
export interface MeterReadingResult {
  type: "meter_reading";
  assetId: string;
  value: number;
  meterReadingId: string;
  /**
   * The reading itself is deferred too, not just the tickets it triggers:
   * writing it early would bump Asset.meter_reading off a number the guard
   * can still correct, and maintenance rules must be evaluated against the
   * value actually submitted.
   */
  pendingReading?: PendingMeterReading;
}

export type ItemResult =
  | SimpleCheckResult
  | VerifyTaskResult
  | DoorCheckResult
  | LocationCheckResult
  | MeterReadingResult;

// ---- Checklist.triggeredBy ----

export type TriggeredBy =
  | { type: "clock_in" | "clock_out"; shiftId: string }
  | { type: "checkpoint"; checkpointId: string; checkInId: string }
  | { type: "scheduled" }
  | { type: "manual" }
  | { type: "incident_type"; incidentId: string }
  | { type: "location_check"; parentChecklistId: string; locationId: string };

export function triggeredByLabel(
  t: TriggeredBy | null | undefined,
  checkpointName?: string,
): string {
  if (!t) return "Manually started";
  switch (t.type) {
    case "clock_in":
      return "Clock In";
    case "clock_out":
      return "Clock Out";
    case "checkpoint":
      return `Checkpoint: ${checkpointName ?? "—"}`;
    case "scheduled":
      return "Scheduled";
    case "manual":
      return "Manual";
    case "incident_type":
      return "Incident";
    case "location_check":
      return "Location-Based Check";
    default:
      return "—";
  }
}

export function doorStateLabel(s: DoorState): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * One reading of a door check across both stored shapes. Historical rows
 * only ever recorded the *last* observed state, so their "as found" value is
 * unknowable — foundKnown says so explicitly rather than quietly implying
 * the door was found correct.
 */
export function doorCheckSummary(r: DoorCheckResult): {
  expected: DoorState;
  initial: DoorState | null;
  final: DoorState | null;
  foundKnown: boolean;
  foundAsExpected: boolean;
  leftAsExpected: boolean;
  corrected: boolean;
  note?: string;
  incidentId?: string;
} {
  const legacyLast = r.attempts?.at(-1)?.observed ?? null;
  const initial = r.initialState ?? null;
  const final = r.finalState ?? legacyLast;
  const foundKnown = r.initialState != null;
  const foundAsExpected = foundKnown && initial === r.expected;
  const leftAsExpected = final != null && final === r.expected;
  return {
    expected: r.expected,
    initial,
    final,
    foundKnown,
    foundAsExpected,
    leftAsExpected,
    corrected: foundKnown && !foundAsExpected && leftAsExpected,
    note: r.note,
    incidentId: r.incidentId,
  };
}

/** Display label for an item type, mapping legacy type strings first. */
export function itemTypeLabel(type: string): string {
  const t = normalizeItemType(type);
  return ITEM_TYPE_LABEL[t as ItemType] ?? type;
}

export const ITEM_TYPE_LABEL: Record<ItemType, string> = {
  simple_check: "Simple Check",
  verify_task: "Verify Task",
  door_check: "Door Check",
  lock_check: "Lock Check",
  location_check: "Location-Based Check",
  meter_reading: "Meter Reading",
};

// ---- ChecklistTemplateSection trigger types ----

export type SectionTriggerType =
  | "manual"
  | "time_window"
  | "checkpoint"
  | "location"
  | "asset";

export interface SectionTriggerConfig {
  /**
   * For "time_window": an RFC 5545 RRULE naming when the window *opens* —
   * e.g. "FREQ=DAILY;BYHOUR=21;BYMINUTE=0" for 9pm nightly. Paired with
   * durationMinutes to make a span; see lib/sectionActivation.ts.
   */
  recurrenceRule?: string;
  /** How long the section stays open from each occurrence. Default 60. */
  durationMinutes?: number;

  // For "checkpoint" / "location" / "asset":
  applicableCheckpoints?: string[];
  applicableLocations?: string[];
  applicableAssets?: string[];
}

/**
 * A section as the UI consumes it: always present, always with its items
 * sorted, whether it came from a real ChecklistTemplateSection row or was
 * synthesised around a legacy template's direct items.
 */
export interface ResolvedSection {
  id: string;
  name: string;
  order: number;
  isActive: boolean;
  triggerType: SectionTriggerType;
  triggerConfig: SectionTriggerConfig;
  items: TemplateItemLike[];
  /** True when this wraps pre-sections items rather than a stored section. */
  synthetic: boolean;
}

/** The parts of a ChecklistTemplateItem every consumer here relies on. */
export interface TemplateItemLike {
  id: string;
  type: string;
  label: string;
  order: number;
  config?: Record<string, unknown>;
}

interface TemplateSectionLike {
  id: string;
  name: string;
  order: number;
  isActive: boolean;
  triggerType: string;
  triggerConfig?: Record<string, unknown>;
  items?: TemplateItemLike[];
}

/** Id of the synthetic section wrapping a legacy template's direct items. */
export const LEGACY_SECTION_ID = "__legacy__";

/**
 * One list of sections for a template regardless of how it was authored.
 *
 * Templates written before sections existed hang their items straight off the
 * template, and those rows are not migrated — the link stays, and they're
 * wrapped here in a single always-on section instead. That keeps every caller
 * on one shape (`section.items`) without a "does this template have sections?"
 * branch at each call site, and means an un-migrated template behaves exactly
 * as it did before: every item visible, no activation filtering.
 *
 * A template with both (mid-migration, or an admin who added a section to an
 * old template) lists the legacy section first, since its items predate the
 * ones deliberately filed into sections.
 */
export function sectionsForTemplate(
  template:
    | {
        items?: TemplateItemLike[];
        sections?: TemplateSectionLike[];
      }
    | null
    | undefined,
): ResolvedSection[] {
  const byOrder = (a: { order: number }, b: { order: number }) => a.order - b.order;

  const stored = (template?.sections ?? []).slice().sort(byOrder).map(
    (s): ResolvedSection => ({
      id: s.id,
      name: s.name,
      order: s.order,
      isActive: s.isActive,
      triggerType: (s.triggerType as SectionTriggerType) ?? "manual",
      triggerConfig: (s.triggerConfig ?? {}) as SectionTriggerConfig,
      items: (s.items ?? []).slice().sort(byOrder),
      synthetic: false,
    }),
  );

  const legacyItems = (template?.items ?? []).slice().sort(byOrder);
  if (legacyItems.length === 0) return stored;

  return [
    {
      id: LEGACY_SECTION_ID,
      name: "Checklist",
      order: -1,
      isActive: true,
      // "manual" is the always-on trigger — an un-sectioned template must keep
      // showing every item, never get filtered out by a time or place rule.
      triggerType: "manual",
      triggerConfig: {},
      items: legacyItems,
      synthetic: true,
    },
    ...stored,
  ];
}

/** Every item across the given sections, in section-then-item order. */
export function itemsOfSections(sections: ResolvedSection[]): TemplateItemLike[] {
  return sections.flatMap((s) => s.items);
}

/**
 * Who a newly created checklist belongs to.
 *
 * "role" deliberately leaves it unassigned, for any holder of the template's
 * role to claim out of the unclaimed queue. But that queue finds checklists
 * by `template.role.id`, so it only works when a role is actually linked —
 * and assignmentMode could be set to "role" independently of ever naming one.
 * The result was a checklist created, owned by nobody, and matched by no
 * query in the app: invisible even to the guard who triggered it. Falling
 * back to the triggering user loses the role routing, which is a much
 * smaller loss than losing the checklist.
 *
 * Callers link `assignedTo` only when this returns "triggering_user".
 */
export function assigneeFor(template: {
  assignmentMode: string;
  role?: { id: string } | null;
}): "triggering_user" | "role" {
  if (template.assignmentMode !== "role") return "triggering_user";
  return template.role ? "role" : "triggering_user";
}

type ChecklistTemplate = InstaQLEntity<AppSchema, "checklistTemplates">;

// Checkpoint-triggered templates carry an optional time-of-day window in
// triggerConfig; every other trigger type (or one with no window configured)
// always applies. Season-based conditions are not modeled yet.
export function templateAppliesNow(
  template: Pick<ChecklistTemplate, "triggerType" | "triggerConfig">,
  now: Date = new Date(),
): boolean {
  if (template.triggerType !== "checkpoint") return true;
  const cfg = (template.triggerConfig ?? {}) as {
    timeStart?: string;
    timeEnd?: string;
  };
  if (!cfg.timeStart || !cfg.timeEnd) return true;
  const [sh, sm] = cfg.timeStart.split(":").map(Number);
  const [eh, em] = cfg.timeEnd.split(":").map(Number);
  const minutes = now.getHours() * 60 + now.getMinutes();
  const start = sh * 60 + sm;
  const end = eh * 60 + em;
  return start <= end
    ? minutes >= start && minutes < end
    : minutes >= start || minutes < end;
}
