// Asset maintenance rules — meter-based rules fire inline on the InstantDB
// write that records a new AssetMeterReading, since that's the only moment
// the value changes.
//
// Time-based rules ("every 90 days since last completed") are not modeled
// here yet. They are specified to run client-side on the same
// deterministic-id pattern as recurring checklists rather than as a scheduled
// function — see docs/adr/0004-client-first-execution.md and
// docs/ROADMAP.md. Nothing generates them today.
import type { InstaQLEntity } from "@instantdb/react";
import type { AppSchema } from "./db";

type Asset = InstaQLEntity<AppSchema, "assets">;
type Ticket = InstaQLEntity<AppSchema, "tickets">;
type MeterReading = InstaQLEntity<AppSchema, "assetMeterReadings">;
type MeterRule = { kind: "meter"; every: number; label?: string };

export function maintenanceRuleTitle(asset: Asset, rule: MeterRule): string {
  return `Maintenance due: ${asset.name} — ${rule.label ?? `every ${rule.every}`}`;
}

// A rule is due once the new reading has advanced far enough past the
// baseline (the reading nearest the last time this same rule's ticket was
// resolved, or the asset's earliest known reading if it's never fired) — and
// only if no ticket for it is already open, to avoid raising duplicates.
export function dueMeterMaintenanceRules(
  asset: Asset,
  newValue: number,
  priorReadings: MeterReading[],
  existingTickets: Ticket[],
): MeterRule[] {
  const rules = (asset.maintenanceRules ?? []).filter(
    (r): r is MeterRule => r.kind === "meter",
  );
  if (rules.length === 0) return [];

  const readingsAsc = [...priorReadings].sort(
    (a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime(),
  );
  const autoTickets = existingTickets.filter((t) => t.autoGenerated);

  return rules.filter((rule) => {
    const title = maintenanceRuleTitle(asset, rule);
    const matching = autoTickets
      .filter((t) => t.title === title)
      .sort(
        (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
      );
    if (matching.some((t) => !t.resolvedAt)) return false;

    const lastResolved = matching.find((t) => t.resolvedAt);
    let baseline = readingsAsc[0]?.value ?? 0;
    if (lastResolved) {
      const resolvedAt = new Date(lastResolved.createdAt).getTime();
      const atOrAfter = readingsAsc.find(
        (r) => new Date(r.timestamp).getTime() >= resolvedAt,
      );
      baseline = atOrAfter?.value ?? newValue;
    }
    return newValue - baseline >= rule.every;
  });
}
