import { useState } from "react";
import type { InstaQLEntity } from "@instantdb/react";
import { db, id, type AppSchema } from "../../lib/db";
import { useCurrent } from "../../lib/auth/CurrentUserContext";
import { formatNumber } from "../../lib/assets";
import {
  dueMeterMaintenanceRules,
  maintenanceRuleTitle,
} from "../../lib/maintenanceRules";
import { activityTx } from "../../lib/activityLog";

type Asset = InstaQLEntity<AppSchema, "assets">;

// Assets — Meter Update Dialog (see docs/pages/meter-update-dialog.html).
// The direct edit path, gated by manage_assets — the Meter Reading checklist
// item captures the same AssetMeterReading unrestricted as part of normal
// checklist completion. Both feed the same inline maintenance-rule check.
export function MeterUpdateDialog({
  asset,
  onClose,
}: {
  asset: Asset;
  onClose: () => void;
}) {
  const current = useCurrent();
  const [value, setValue] = useState("");
  const [correctionReason, setCorrectionReason] = useState("");
  const [saving, setSaving] = useState(false);

  const currentValue = asset.meterReading ?? 0;
  const entered = value === "" ? null : Number(value);

  // Metered assets take an absolute reading; meterless ones accrue hours, so
  // the entry is a delta added to the running total.
  const newTotal =
    entered == null ? null : asset.hasMeter ? entered : currentValue + entered;
  const isCorrection =
    asset.hasMeter && entered != null && entered < currentValue;

  const save = async () => {
    if (newTotal == null) return;
    setSaving(true);

    const { data: fresh } = await db.queryOnce({
      assetMeterReadings: { $: { where: { "asset.id": asset.id } } },
      tickets: { $: { where: { "asset.id": asset.id } } },
    });
    const dueRules = dueMeterMaintenanceRules(
      asset,
      newTotal,
      fresh?.assetMeterReadings ?? [],
      fresh?.tickets ?? [],
    );

    await db.transact([
      db.tx.assetMeterReadings[id()]
        .update({
          value: newTotal,
          source: "manual",
          timestamp: Date.now(),
          ...(isCorrection ? { correctionReason: correctionReason.trim() } : {}),
        })
        .link({
          asset: asset.id,
          ...(current.user ? { loggedBy: current.user.id } : {}),
        }),
      db.tx.assets[asset.id].update({ meterReading: newTotal }),
      activityTx({
        eventType: "asset.meter_updated",
        summary:
          `${asset.name} meter set to ${newTotal}` +
          (isCorrection ? ` (correction: ${correctionReason.trim()})` : ""),
        subjectType: "assets",
        subjectId: asset.id,
        actorId: current.user?.id,
      }),
      // A due rule raises its ticket inline, not on a delayed sweep.
      ...dueRules.map((rule) =>
        db.tx.tickets[id()]
          .update({
            title: maintenanceRuleTitle(asset, rule),
            priority: "medium",
            status: "open",
            autoGenerated: true,
            createdAt: Date.now(),
          })
          .link({ asset: asset.id }),
      ),
    ]);
    onClose();
  };

  const unit = asset.hasMeter
    ? asset.meterType === "mileage"
      ? "mi"
      : "hrs"
    : "hrs";

  return (
    <div className="dialog-backdrop" onClick={onClose}>
      <div className="dialog-card" onClick={(e) => e.stopPropagation()}>
        <div className="card-title" style={{ marginBottom: 10 }}>
          Update meter — {asset.name}
        </div>

        <div className="field">
          <span className="field-label">
            {asset.hasMeter ? "Current reading" : "Hours accrued so far"}
          </span>
          <div className="field-value">
            {formatNumber(currentValue)} {unit}
          </div>
        </div>

        <div className="field">
          <span className="field-label">
            {asset.hasMeter
              ? `New reading (${unit}) — absolute value`
              : "Hours to add"}
          </span>
          <input
            type="number"
            className="input"
            value={value}
            onChange={(e) => setValue(e.target.value)}
            autoFocus
          />
          {!asset.hasMeter && newTotal != null && (
            <p className="muted small" style={{ marginTop: 4 }}>
              New total: {formatNumber(newTotal)} {unit}
            </p>
          )}
        </div>

        {isCorrection && (
          <div className="field">
            <span className="badge badge-warn" style={{ marginBottom: 6 }}>
              Lower than the current reading
            </span>
            <span className="field-label">Reason — required</span>
            <textarea
              className="textarea"
              rows={2}
              value={correctionReason}
              onChange={(e) => setCorrectionReason(e.target.value)}
              placeholder="e.g. meter replaced, previous entry corrected"
            />
          </div>
        )}

        <div className="row">
          <button
            type="button"
            className="btn btn-primary"
            disabled={
              newTotal == null ||
              saving ||
              (isCorrection && !correctionReason.trim())
            }
            onClick={() => void save()}
          >
            Save
          </button>
          <button type="button" className="btn btn-quiet" onClick={onClose}>
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
}
