import { faker } from "@faker-js/faker";
import type { InstaQLEntity } from "@instantdb/react";
import type { AppSchema } from "../lib/db";

/**
 * Fixture factories for the unit suite.
 *
 * Faker supplies *incidental* data — the filler contacts in a list, a
 * plausible slip name, a phone number — so fixtures read like marina data
 * instead of "foo" and "bar". The seed is pinned in setup.ts.
 *
 * The rule that keeps this honest: **faker never generates the value under
 * test.** "Slip 9 sorts before Slip 14" *is* the assertion, so those are
 * literals; the other twelve slips in the list can be faker's problem. A
 * random value in an assertion position makes a failure unreadable.
 *
 * The casts live here rather than in test files. `dueMeterMaintenanceRules`
 * takes full InstaQL entities, and constructing every field of an Asset to
 * exercise two of them would obscure what each test is actually about.
 */

type Asset = InstaQLEntity<AppSchema, "assets">;
type Ticket = InstaQLEntity<AppSchema, "tickets">;
type MeterReading = InstaQLEntity<AppSchema, "assetMeterReadings">;

export interface RoleFixture {
  name: string;
  allow?: string[];
  deny?: string[];
}

export function aRole(over: Partial<RoleFixture> = {}): RoleFixture {
  return { name: faker.person.jobTitle(), allow: [], deny: [], ...over };
}

export interface ContactFixture {
  id: string;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  mergedInto?: { id: string } | null;
}

export function aContact(over: Partial<ContactFixture> = {}): ContactFixture {
  return {
    id: faker.string.uuid(),
    name: faker.person.fullName(),
    phone: faker.phone.number({ style: "national" }),
    email: faker.internet.email(),
    mergedInto: null,
    ...over,
  };
}

export function anAsset(over: Partial<Asset> = {}): Asset {
  return {
    id: faker.string.uuid(),
    name: faker.commerce.productName(),
    hasMeter: true,
    checkoutable: false,
    reservationEnabled: false,
    maintenanceRules: [],
    ...over,
  } as unknown as Asset;
}

export function aMeterReading(over: Partial<MeterReading> = {}): MeterReading {
  return {
    id: faker.string.uuid(),
    value: 0,
    source: "manual",
    timestamp: new Date("2026-01-01T00:00:00Z").getTime(),
    ...over,
  } as unknown as MeterReading;
}

export function aTicket(over: Partial<Ticket> = {}): Ticket {
  return {
    id: faker.string.uuid(),
    title: faker.lorem.sentence(),
    priority: "medium",
    status: "open",
    autoGenerated: true,
    createdAt: new Date("2026-01-01T00:00:00Z").getTime(),
    ...over,
  } as unknown as Ticket;
}

export interface LocationFixture {
  id: string;
  name: string;
  parent?: { id: string } | null;
}

export function aLocation(over: Partial<LocationFixture> = {}): LocationFixture {
  return { id: faker.string.uuid(), name: faker.location.street(), parent: null, ...over };
}

export function aCheckpoint(
  over: Partial<{ id: string; name: string; location?: { id: string; name: string } | null }> = {},
) {
  return { id: faker.string.uuid(), name: faker.lorem.word(), location: null, ...over };
}
