import { useState } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import type { InstaQLEntity } from "@instantdb/react";
import { db, id, type AppSchema } from "../../lib/db";
import { useCurrent } from "../../lib/auth/CurrentUserContext";
import { deterministicId } from "../../lib/detId";
import { dueMeterMaintenanceRules, maintenanceRuleTitle } from "../../lib/maintenanceRules";
import { doorCheckSummary, doorStateLabel } from "../../lib/checklists";
import type {
  DoorCheckConfig,
  DoorState,
  ItemResult,
  LocationCheckConfig,
  MeterReadingConfig,
  VerifyTaskConfig,
} from "../../lib/checklists";
import { attachmentLink, type AttachmentTarget } from "../../lib/attachments";
import { AttachmentTargetPicker } from "../shared/AttachmentTargetPicker";
import { activityTx } from "../../lib/activityLog";

type TemplateItem = InstaQLEntity<AppSchema, "checklistTemplateItems">;
type ItemResultEntity = InstaQLEntity<
  AppSchema,
  "checklistItemResults",
  { linkedTicket: object }
>;

export interface ItemProps {
  item: TemplateItem;
  existing: ItemResultEntity | undefined;
  checklistId: string;
  onSaved: (result: ItemResult, ticketId?: string) => void;
}

const DOOR_STATES: DoorState[] = ["open", "unlocked", "locked"];

async function saveResult(
  checklistId: string,
  itemId: string,
  existingId: string | undefined,
  result: ItemResult,
  linkedTicketId?: string,
) {
  const resultId = existingId ?? id();
  await db.transact(
    db.tx.checklistItemResults[resultId]
      .update({ result: result as unknown as Record<string, unknown>, completedAt: Date.now() })
      .link({
        checklist: checklistId,
        templateItem: itemId,
        ...(linkedTicketId ? { linkedTicket: linkedTicketId } : {}),
      }),
  );
}

// ---------------------------------------------------------------- Simple Check

export function SimpleCheckItem({ item, existing, checklistId, onSaved }: ItemProps) {
  const done = existing?.result != null;
  const complete = async () => {
    const result: ItemResult = { type: "simple_check", completedAt: Date.now() };
    await saveResult(checklistId, item.id, existing?.id, result);
    onSaved(result);
  };
  return (
    <div className={"card" + (done ? " card-done" : "")}>
      <div className="badge">Simple Check</div>
      <div className="card-title">{item.label}</div>
      {done ? (
        <div className="card-meta">✓ Complete</div>
      ) : (
        <div className="row" style={{ marginTop: 10 }}>
          <button type="button" className="btn btn-primary" onClick={() => void complete()}>
            ✓ Mark complete
          </button>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------- Verify Task

export function VerifyTaskItem({ item, existing, checklistId, onSaved }: ItemProps) {
  const cfg = (item.config ?? {}) as unknown as VerifyTaskConfig;
  const existingResult = existing?.result as
    | Extract<ItemResult, { type: "verify_task" }>
    | undefined;
  const [stage, setStage] = useState<"initial" | "attempt" | "reason">("initial");
  const [reason, setReason] = useState("");
  const done = existingResult != null;

  const finish = async (
    outcome: "confirmed" | "rejected_reason" | "rejected_ticket",
    attempted?: boolean,
  ) => {
    const result: ItemResult = {
      type: "verify_task",
      outcome,
      attempted,
      ...(outcome === "rejected_reason" ? { reason } : {}),
    };
    let ticketId: string | undefined;
    if (outcome === "rejected_ticket") {
      ticketId = id();
      await db.transact(
        db.tx.tickets[ticketId].update({
          title: `Failed Verify Task: ${item.label}`,
          priority: "medium",
          status: "open",
          autoGenerated: false,
          createdAt: Date.now(),
        }),
      );
    }
    await saveResult(checklistId, item.id, existing?.id, result, ticketId);
    onSaved(result, ticketId);
  };

  const clickReject = () => {
    if (cfg.requireAttemptBeforeReject && stage === "initial") setStage("attempt");
    else setStage("reason");
  };

  if (done) {
    return (
      <div className="card card-done">
        <div className="badge">Verify Task</div>
        <div className="card-title">{item.label}</div>
        <div className="card-meta">{verifyOutcomeLabel(existingResult)}</div>
      </div>
    );
  }

  return (
    <div className="card">
      <div className="badge">Verify Task</div>
      <div className="card-title">{item.label}</div>

      {stage === "initial" && (
        <div className="row" style={{ marginTop: 10, flexWrap: "wrap" }}>
          <button
            type="button"
            className="btn btn-primary"
            onClick={() => void finish("confirmed")}
          >
            Confirm
          </button>
          <button type="button" className="btn" onClick={clickReject}>
            Reject — reason
          </button>
          <button type="button" className="btn btn-danger" onClick={() => void finish("rejected_ticket")}>
            Reject — raise ticket
          </button>
        </div>
      )}

      {stage === "attempt" && (
        <div style={{ marginTop: 10 }}>
          <p className="muted small">
            Attempt the task yourself before finalizing a rejection.
          </p>
          <div className="row">
            <button
              type="button"
              className="btn btn-primary"
              onClick={() => void finish("confirmed", true)}
            >
              I did it — Confirm
            </button>
            <button type="button" className="btn btn-danger" onClick={() => setStage("reason")}>
              Still rejecting
            </button>
          </div>
        </div>
      )}

      {stage === "reason" && (
        <div style={{ marginTop: 10 }}>
          <div className="field">
            <span className="field-label">Reason</span>
            <textarea
              className="textarea"
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              rows={3}
            />
          </div>
          <div className="row">
            <button
              type="button"
              className="btn btn-primary"
              disabled={!reason.trim()}
              onClick={() => void finish("rejected_reason")}
            >
              Reject with reason
            </button>
            <button type="button" className="btn btn-quiet" onClick={() => setStage("initial")}>
              Cancel
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function verifyOutcomeLabel(r: Extract<ItemResult, { type: "verify_task" }>): string {
  if (r.outcome === "confirmed") return r.attempted ? "Confirmed (after attempt)" : "Confirmed";
  if (r.outcome === "rejected_reason") return `Rejected — ${r.reason ?? "reason given"}`;
  return "Rejected — ticket raised";
}

// ---------------------------------------------------------------- Door Check

/**
 * A door check records two facts, not one: the state the door was *found*
 * in, and the state it was *left* in. Only the pair supports the questions
 * the reports need to answer — "was this door actually secure overnight?"
 * and, separately, "did the guard put it right?" — which a single observed
 * state silently conflated.
 *
 * Found-as-expected is the overwhelmingly common case and stays one tap: the
 * final state is implied and the second row of buttons never appears. A
 * mismatch is the exceptional path, and it's the one worth slowing down —
 * it logs an incident (the door was wrong before anyone touched it, which is
 * true regardless of what happens next) and then asks what state the guard
 * managed to leave it in.
 */
export function DoorCheckItem({ item, existing, checklistId, onSaved }: ItemProps) {
  const cfg = (item.config ?? {}) as unknown as DoorCheckConfig;
  // An item whose config was never opened in the template builder persists
  // as `{}` — the builder only shows "Locked" as the select's default, it
  // never writes it. Default here too, matching that displayed default,
  // rather than crashing stateLabel() on an undefined state.
  const expectedState: DoorState = cfg.expectedState ?? "locked";
  const current = useCurrent();
  const existingResult = existing?.result as
    | Extract<ItemResult, { type: "door_check" }>
    | undefined;

  const [initialState, setInitialState] = useState<DoorState | null>(null);
  const [pendingFinal, setPendingFinal] = useState<DoorState | null>(null);
  const [title, setTitle] = useState("");
  const [details, setDetails] = useState("");
  const [target, setTarget] = useState<AttachmentTarget | null>(null);
  const [saving, setSaving] = useState(false);
  const done = existingResult != null;

  // The door's bound Location is the incident's attachment target. Items
  // authored before that binding existed have none, so the guard picks one
  // rather than the incident silently failing to save.
  const { data: boundData } = db.useQuery(
    cfg.locationId ? { locations: { $: { where: { id: cfg.locationId } } } } : null,
  );
  const boundLocation = boundData?.locations?.[0];
  const effectiveTarget: AttachmentTarget | null = boundLocation
    ? { type: "location", id: boundLocation.id, label: boundLocation.name }
    : target;

  const beginMismatch = (found: DoorState) => {
    setInitialState(found);
    setTitle(`${item.label} found ${stateLabel(found).toLowerCase()}`);
    setDetails(
      `Expected ${stateLabel(expectedState).toLowerCase()}, ` +
        `found ${stateLabel(found).toLowerCase()}.`,
    );
  };

  const selectInitial = async (found: DoorState) => {
    if (found !== expectedState) {
      beginMismatch(found);
      return;
    }
    // Found as expected: nothing to correct, so the final state is the same
    // state and the guard is never asked a second question.
    const result: ItemResult = {
      type: "door_check",
      expected: expectedState,
      initialState: found,
      finalState: found,
    };
    await saveResult(checklistId, item.id, existing?.id, result);
    onSaved(result);
  };

  // Everything a mismatch produces — the incident, an optional ticket, and
  // the result itself — is written in one transaction at the end, so
  // abandoning the item mid-flow can't leave an orphaned incident behind.
  const commitMismatch = async (finalState: DoorState, raiseTicket: boolean) => {
    if (!initialState || saving) return;
    setSaving(true);
    try {
      const incidentId = id();
      const ticketId = raiseTicket ? id() : undefined;
      const summary =
        `${item.label}: found ${stateLabel(initialState).toLowerCase()}, ` +
        `left ${stateLabel(finalState).toLowerCase()} ` +
        `(expected ${stateLabel(expectedState).toLowerCase()})`;
      const result: ItemResult = {
        type: "door_check",
        expected: expectedState,
        initialState,
        finalState,
        ...(details.trim() ? { note: details.trim() } : {}),
        incidentId,
      };
      await db.transact([
        db.tx.incidents[incidentId]
          .update({
            title: title.trim() || summary,
            status: "open",
            details: details.trim() || undefined,
            createdAt: Date.now(),
          })
          .link({
            ...(effectiveTarget ? attachmentLink(effectiveTarget) : {}),
            ...(current.user ? { author: current.user.id } : {}),
          }),
        activityTx({
          eventType: "incident.created",
          summary,
          subjectType: "incidents",
          subjectId: incidentId,
          actorId: current.user?.id,
        }),
        ...(ticketId
          ? [
              db.tx.tickets[ticketId]
                .update({
                  title: `Door left ${stateLabel(finalState).toLowerCase()}: ${item.label}`,
                  description: summary,
                  priority: "medium",
                  status: "open",
                  autoGenerated: false,
                  createdAt: Date.now(),
                })
                .link({ sourceIncident: incidentId }),
            ]
          : []),
      ]);
      await saveResult(checklistId, item.id, existing?.id, result, ticketId);
      onSaved(result, ticketId);
    } finally {
      setSaving(false);
    }
  };

  const chooseFinal = (finalState: DoorState) => {
    if (finalState === expectedState) {
      // Put right — no ticket to offer, so don't ask.
      void commitMismatch(finalState, false);
      return;
    }
    setPendingFinal(finalState);
  };

  if (done) {
    const s = doorCheckSummary(existingResult);
    return (
      <div className={"card" + (s.leftAsExpected ? " card-done" : "")}>
        <div className="badge">Door Check</div>
        <div className="card-title">{item.label}</div>
        <div className="card-meta">{doneSummaryText(s)}</div>
      </div>
    );
  }

  // Mismatch flow: incident details, then the second row of buttons.
  if (initialState) {
    return (
      <div className="card">
        <div className="badge">Door Check</div>
        <div className="card-title">{item.label}</div>
        <div className="badge badge-bad" style={{ margin: "8px 0", display: "block" }}>
          Found {stateLabel(initialState).toLowerCase()} — expected{" "}
          {stateLabel(expectedState).toLowerCase()}. This is logged as an incident.
        </div>

        <div className="field">
          <span className="field-label">Incident title</span>
          <input
            className="input"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
        </div>
        <div className="field">
          <span className="field-label">Details</span>
          <textarea
            className="textarea"
            rows={2}
            value={details}
            onChange={(e) => setDetails(e.target.value)}
          />
        </div>
        {boundLocation ? (
          <div className="field">
            <span className="field-label">Attached to</span>
            <div className="field-value">{boundLocation.name}</div>
          </div>
        ) : (
          <div className="field">
            <span className="field-label">
              Attach to — this door has no location set in its template
            </span>
            <AttachmentTargetPicker value={target} onChange={setTarget} />
          </div>
        )}

        <div className="field-label" style={{ marginTop: 4 }}>
          What state did you leave it in?
        </div>
        <div className="row" style={{ flexWrap: "wrap" }}>
          {DOOR_STATES.map((s) => (
            <button
              key={s}
              type="button"
              className={
                "btn btn-sm" + (pendingFinal === s ? " btn-primary" : "")
              }
              disabled={saving}
              onClick={() => chooseFinal(s)}
            >
              {stateLabel(s)}
            </button>
          ))}
        </div>

        {pendingFinal && pendingFinal !== expectedState && (
          <div style={{ marginTop: 10 }}>
            <div className="badge badge-warn" style={{ marginBottom: 8, display: "block" }}>
              Leaving it {stateLabel(pendingFinal).toLowerCase()} — still not the
              expected state. Raise a ticket so it gets followed up?
            </div>
            <div className="row" style={{ flexWrap: "wrap" }}>
              <button
                type="button"
                className="btn btn-sm btn-danger"
                disabled={saving}
                onClick={() => void commitMismatch(pendingFinal, true)}
              >
                Save &amp; raise a ticket
              </button>
              <button
                type="button"
                className="btn btn-sm"
                disabled={saving}
                onClick={() => void commitMismatch(pendingFinal, false)}
              >
                Save without a ticket
              </button>
            </div>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="card">
      <div className="badge">Door Check</div>
      <div className="card-title">{item.label}</div>
      <div className="field-label" style={{ marginTop: 10 }}>
        Expected: {stateLabel(expectedState)} · how did you find it?
      </div>
      <div className="row" style={{ flexWrap: "wrap", marginTop: 8 }}>
        {DOOR_STATES.map((s) => (
          <button key={s} type="button" className="btn btn-sm" onClick={() => void selectInitial(s)}>
            {stateLabel(s)}
          </button>
        ))}
      </div>
    </div>
  );
}

function doneSummaryText(s: ReturnType<typeof doorCheckSummary>): string {
  // Historical rows never stored an "as found" state, so say what's actually
  // known rather than implying the door was found correct.
  if (!s.foundKnown) {
    return s.final
      ? `${stateLabel(s.final)}${s.leftAsExpected ? " (matched)" : " — mismatch"}`
      : "Recorded";
  }
  if (s.foundAsExpected) return `Found ${stateLabel(s.initial!).toLowerCase()} — as expected`;
  if (s.corrected)
    return `Found ${stateLabel(s.initial!).toLowerCase()} — corrected to ${stateLabel(s.final!).toLowerCase()}`;
  return `Found ${stateLabel(s.initial!).toLowerCase()} — left ${stateLabel(s.final!).toLowerCase()}, still not as expected`;
}

function stateLabel(s: DoorState): string {
  return doorStateLabel(s);
}


// ---------------------------------------------------------------- Location-Based Check

export function LocationCheckItem({ item, existing, checklistId, onSaved }: ItemProps) {
  const cfg = (item.config ?? {}) as unknown as LocationCheckConfig;
  const existingResult = existing?.result as
    | Extract<ItemResult, { type: "location_check" }>
    | undefined;
  const navigate = useNavigate();
  const location = useLocation();
  const current = useCurrent();

  const { data: nestedData } = db.useQuery(
    existingResult
      ? { checklists: { $: { where: { id: existingResult.nestedChecklistId } } } }
      : null,
  );
  const { data: locationData } = db.useQuery(
    !existingResult ? { locations: { $: { where: { id: cfg.locationId } } } } : null,
  );
  const nested = nestedData?.checklists?.[0];
  const locationName = locationData?.locations?.[0]?.name;
  const nestedComplete = nested?.status === "complete";

  const open = async () => {
    let nestedId = existingResult?.nestedChecklistId;
    if (!nestedId) {
      nestedId = deterministicId(`location-check:${checklistId}:${item.id}`);
      await db.transact([
        db.tx.checklists[nestedId]
          .update({
            status: "not_started",
            triggeredBy: {
              type: "location_check",
              parentChecklistId: checklistId,
              locationId: cfg.locationId,
            },
          })
          .link({ template: cfg.templateId, ...(current.user ? { assignedTo: current.user.id } : {}) }),
        db.tx.checklistItemResults[existing?.id ?? id()]
          .update({ result: { type: "location_check", nestedChecklistId: nestedId } })
          .link({ checklist: checklistId, templateItem: item.id }),
      ]);
      onSaved({ type: "location_check", nestedChecklistId: nestedId });
    }
    navigate(`/checklists/${nestedId}`, { state: { returnTo: location.pathname } });
  };

  return (
    <div className={"card" + (nestedComplete ? " card-done" : "")}>
      <div className="badge">Location-Based Check</div>
      <div className="card-title">{item.label}</div>
      <div className="card-meta">
        {locationName ? `Scoped to ${locationName}` : "Opens a nested sub-checklist"}
      </div>
      <div className="row" style={{ marginTop: 10 }}>
        <button type="button" className="btn" onClick={() => void open()}>
          {existingResult ? (nestedComplete ? "View nested checklist" : "Resume nested checklist") : "Open nested checklist"}
        </button>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------- Meter Reading

export function MeterReadingItem({ item, existing, checklistId, onSaved }: ItemProps) {
  const cfg = (item.config ?? {}) as unknown as MeterReadingConfig;
  const existingResult = existing?.result as
    | Extract<ItemResult, { type: "meter_reading" }>
    | undefined;
  const [assetId, setAssetId] = useState(cfg.assetId ?? "");
  const [value, setValue] = useState("");
  const [correctionReason, setCorrectionReason] = useState("");

  const { data } = db.useQuery(
    cfg.assetId
      ? { assets: { $: { where: { id: cfg.assetId } } } }
      : { assets: { $: { where: { hasMeter: true } } } },
  );
  const options = cfg.assetId ? [] : data?.assets ?? [];
  const asset = cfg.assetId ? data?.assets?.[0] : options.find((a) => a.id === assetId);

  const done = existingResult != null;
  const needsCorrection =
    asset?.meterReading != null && Number(value) < asset.meterReading && value !== "";

  const record = async () => {
    if (!asset) return;
    const numeric = Number(value);
    const readingId = id();
    const { data: fresh } = await db.queryOnce({
      assetMeterReadings: { $: { where: { "asset.id": asset.id } } },
      tickets: { $: { where: { "asset.id": asset.id } } },
    });
    const dueRules = dueMeterMaintenanceRules(
      asset,
      numeric,
      fresh?.assetMeterReadings ?? [],
      fresh?.tickets ?? [],
    );
    const ticketTxns = dueRules.map((rule) =>
      db.tx.tickets[id()]
        .update({
          title: maintenanceRuleTitle(asset, rule),
          priority: "medium",
          status: "open",
          autoGenerated: true,
          createdAt: Date.now(),
        })
        .link({ asset: asset.id }),
    );
    await db.transact([
      db.tx.assetMeterReadings[readingId]
        .update({
          value: numeric,
          source: "checklist_item",
          timestamp: Date.now(),
          ...(needsCorrection ? { correctionReason } : {}),
        })
        .link({ asset: asset.id }),
      db.tx.assets[asset.id].update({ meterReading: numeric }),
      ...ticketTxns,
    ]);
    const result: ItemResult = {
      type: "meter_reading",
      assetId: asset.id,
      value: numeric,
      meterReadingId: readingId,
    };
    await saveResult(checklistId, item.id, existing?.id, result);
    onSaved(result);
  };

  if (done) {
    return (
      <div className="card card-done">
        <div className="badge">Meter Reading</div>
        <div className="card-title">{item.label}</div>
        <div className="card-meta">Recorded {existingResult.value}</div>
      </div>
    );
  }

  return (
    <div className="card">
      <div className="badge">Meter Reading</div>
      <div className="card-title">{item.label}</div>

      {!cfg.assetId && (
        <div className="field">
          <span className="field-label">Asset</span>
          <select className="select" value={assetId} onChange={(e) => setAssetId(e.target.value)}>
            <option value="">Select…</option>
            {options.map((a) => (
              <option key={a.id} value={a.id}>
                {a.name}
              </option>
            ))}
          </select>
        </div>
      )}
      <div className="field">
        <span className="field-label">
          Reading{asset?.meterReading != null ? ` (current: ${asset.meterReading})` : ""}
        </span>
        <input
          className="input"
          type="number"
          value={value}
          onChange={(e) => setValue(e.target.value)}
        />
      </div>
      {needsCorrection && (
        <div className="field">
          <span className="field-label">
            Correction reason — required (reading is lower than the last one)
          </span>
          <textarea
            className="textarea"
            value={correctionReason}
            onChange={(e) => setCorrectionReason(e.target.value)}
            rows={2}
          />
        </div>
      )}
      <div className="row" style={{ marginTop: 8 }}>
        <button
          type="button"
          className="btn btn-primary"
          disabled={!asset || value === "" || (needsCorrection && !correctionReason.trim())}
          onClick={() => void record()}
        >
          Record reading
        </button>
      </div>
    </div>
  );
}
