import { useState } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import type { InstaQLEntity } from "@instantdb/react";
import { db, id, type AppSchema } from "../../lib/db";
import { useCurrent } from "../../lib/auth/CurrentUserContext";
import { deterministicId } from "../../lib/detId";
import { dueMeterMaintenanceRules, maintenanceRuleTitle } from "../../lib/maintenanceRules";
import type {
  DoorCheckConfig,
  DoorState,
  ItemResult,
  LocationCheckConfig,
  MeterReadingConfig,
  VerifyTaskConfig,
} from "../../lib/checklists";

type TemplateItem = InstaQLEntity<AppSchema, "checklistTemplateItems">;
type ItemResultEntity = InstaQLEntity<
  AppSchema,
  "checklistItemResults",
  { linkedTicket: object }
>;

export interface ItemProps {
  item: TemplateItem;
  existing: ItemResultEntity | undefined;
  checklistId: string;
  onSaved: (result: ItemResult, ticketId?: string) => void;
}

const DOOR_STATES: DoorState[] = ["open", "closed", "locked", "unlocked"];

async function saveResult(
  checklistId: string,
  itemId: string,
  existingId: string | undefined,
  result: ItemResult,
  linkedTicketId?: string,
) {
  const resultId = existingId ?? id();
  await db.transact(
    db.tx.checklistItemResults[resultId]
      .update({ result: result as unknown as Record<string, unknown>, completedAt: Date.now() })
      .link({
        checklist: checklistId,
        templateItem: itemId,
        ...(linkedTicketId ? { linkedTicket: linkedTicketId } : {}),
      }),
  );
}

// ---------------------------------------------------------------- Simple Check

export function SimpleCheckItem({ item, existing, checklistId, onSaved }: ItemProps) {
  const done = existing?.result != null;
  const complete = async () => {
    const result: ItemResult = { type: "simple_check", completedAt: Date.now() };
    await saveResult(checklistId, item.id, existing?.id, result);
    onSaved(result);
  };
  return (
    <div className={"card" + (done ? " card-done" : "")}>
      <div className="badge">Simple Check</div>
      <div className="card-title">{item.label}</div>
      {done ? (
        <div className="card-meta">✓ Complete</div>
      ) : (
        <div className="row" style={{ marginTop: 10 }}>
          <button type="button" className="btn btn-primary" onClick={() => void complete()}>
            ✓ Mark complete
          </button>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------- Verify Task

export function VerifyTaskItem({ item, existing, checklistId, onSaved }: ItemProps) {
  const cfg = (item.config ?? {}) as unknown as VerifyTaskConfig;
  const existingResult = existing?.result as
    | Extract<ItemResult, { type: "verify_task" }>
    | undefined;
  const [stage, setStage] = useState<"initial" | "attempt" | "reason">("initial");
  const [reason, setReason] = useState("");
  const done = existingResult != null;

  const finish = async (
    outcome: "confirmed" | "rejected_reason" | "rejected_ticket",
    attempted?: boolean,
  ) => {
    const result: ItemResult = {
      type: "verify_task",
      outcome,
      attempted,
      ...(outcome === "rejected_reason" ? { reason } : {}),
    };
    let ticketId: string | undefined;
    if (outcome === "rejected_ticket") {
      ticketId = id();
      await db.transact(
        db.tx.tickets[ticketId].update({
          title: `Failed Verify Task: ${item.label}`,
          priority: "medium",
          status: "open",
          autoGenerated: false,
          createdAt: Date.now(),
        }),
      );
    }
    await saveResult(checklistId, item.id, existing?.id, result, ticketId);
    onSaved(result, ticketId);
  };

  const clickReject = () => {
    if (cfg.requireAttemptBeforeReject && stage === "initial") setStage("attempt");
    else setStage("reason");
  };

  if (done) {
    return (
      <div className="card card-done">
        <div className="badge">Verify Task</div>
        <div className="card-title">{item.label}</div>
        <div className="card-meta">{verifyOutcomeLabel(existingResult)}</div>
      </div>
    );
  }

  return (
    <div className="card">
      <div className="badge">Verify Task</div>
      <div className="card-title">{item.label}</div>

      {stage === "initial" && (
        <div className="row" style={{ marginTop: 10, flexWrap: "wrap" }}>
          <button
            type="button"
            className="btn btn-primary"
            onClick={() => void finish("confirmed")}
          >
            Confirm
          </button>
          <button type="button" className="btn" onClick={clickReject}>
            Reject — reason
          </button>
          <button type="button" className="btn btn-danger" onClick={() => void finish("rejected_ticket")}>
            Reject — raise ticket
          </button>
        </div>
      )}

      {stage === "attempt" && (
        <div style={{ marginTop: 10 }}>
          <p className="muted small">
            Attempt the task yourself before finalizing a rejection.
          </p>
          <div className="row">
            <button
              type="button"
              className="btn btn-primary"
              onClick={() => void finish("confirmed", true)}
            >
              I did it — Confirm
            </button>
            <button type="button" className="btn btn-danger" onClick={() => setStage("reason")}>
              Still rejecting
            </button>
          </div>
        </div>
      )}

      {stage === "reason" && (
        <div style={{ marginTop: 10 }}>
          <div className="field">
            <span className="field-label">Reason</span>
            <textarea
              className="textarea"
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              rows={3}
            />
          </div>
          <div className="row">
            <button
              type="button"
              className="btn btn-primary"
              disabled={!reason.trim()}
              onClick={() => void finish("rejected_reason")}
            >
              Reject with reason
            </button>
            <button type="button" className="btn btn-quiet" onClick={() => setStage("initial")}>
              Cancel
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function verifyOutcomeLabel(r: Extract<ItemResult, { type: "verify_task" }>): string {
  if (r.outcome === "confirmed") return r.attempted ? "Confirmed (after attempt)" : "Confirmed";
  if (r.outcome === "rejected_reason") return `Rejected — ${r.reason ?? "reason given"}`;
  return "Rejected — ticket raised";
}

// ---------------------------------------------------------------- Door Check

export function DoorCheckItem({ item, existing, checklistId, onSaved }: ItemProps) {
  const cfg = (item.config ?? {}) as unknown as DoorCheckConfig;
  // An item whose config was never opened in the template builder persists
  // as `{}` — the builder only shows "Locked" as the select's default, it
  // never writes it. Default here too, matching that displayed default,
  // rather than crashing stateLabel() on an undefined state.
  const expectedState: DoorState = cfg.expectedState ?? "locked";
  const existingResult = existing?.result as
    | Extract<ItemResult, { type: "door_check" }>
    | undefined;
  const [attempts, setAttempts] = useState<{ observed: DoorState; matched: boolean }[]>([]);
  const [note, setNote] = useState("");
  const done = existingResult != null;

  const select = async (observed: DoorState) => {
    const matched = observed === expectedState;
    const nextAttempts = [...attempts, { observed, matched }];
    if (matched) {
      const result: ItemResult = {
        type: "door_check",
        expected: expectedState,
        attempts: nextAttempts,
        resolution: "matched",
      };
      await saveResult(checklistId, item.id, existing?.id, result);
      onSaved(result);
      return;
    }
    setAttempts(nextAttempts);
  };

  const resolveWithNote = async () => {
    const result: ItemResult = {
      type: "door_check",
      expected: expectedState,
      attempts,
      resolution: "note",
      note,
    };
    await saveResult(checklistId, item.id, existing?.id, result);
    onSaved(result);
  };

  const resolveWithTicket = async () => {
    const ticketId = id();
    await db.transact(
      db.tx.tickets[ticketId].update({
        title: `Door Check mismatch: ${item.label}`,
        description: `Expected ${expectedState}, observed ${attempts.at(-1)?.observed}.`,
        priority: "medium",
        status: "open",
        autoGenerated: false,
        createdAt: Date.now(),
      }),
    );
    const result: ItemResult = {
      type: "door_check",
      expected: expectedState,
      attempts,
      resolution: "ticket",
    };
    await saveResult(checklistId, item.id, existing?.id, result, ticketId);
    onSaved(result, ticketId);
  };

  if (done) {
    return (
      <div className="card card-done">
        <div className="badge">Door Check</div>
        <div className="card-title">{item.label}</div>
        <div className="card-meta">
          {existingResult.resolution === "matched"
            ? `Observed ${existingResult.attempts.at(-1)?.observed} (matched)`
            : `Mismatch — resolved via ${existingResult.resolution}`}
        </div>
      </div>
    );
  }

  const secondMismatch = attempts.length >= 2 && !attempts.at(-1)?.matched;

  return (
    <div className="card">
      <div className="badge">Door Check</div>
      <div className="card-title">{item.label}</div>
      <div className="field-label" style={{ marginTop: 10 }}>
        Expected: {stateLabel(expectedState)}
      </div>

      {attempts.length > 0 && !secondMismatch && (
        <div className="badge badge-bad" style={{ margin: "6px 0" }}>
          Observed: {stateLabel(attempts.at(-1)!.observed)} — mismatch. Correct it, then select
          again.
        </div>
      )}

      {!secondMismatch && (
        <div className="row" style={{ flexWrap: "wrap", marginTop: 8 }}>
          {DOOR_STATES.map((s) => (
            <button key={s} type="button" className="btn btn-sm" onClick={() => void select(s)}>
              {stateLabel(s)}
            </button>
          ))}
        </div>
      )}

      {secondMismatch && (
        <div style={{ marginTop: 10 }}>
          <div className="badge badge-bad" style={{ marginBottom: 8 }}>
            Still mismatched — a note or ticket is required.
          </div>
          <div className="field">
            <span className="field-label">Note (optional if raising a ticket)</span>
            <textarea
              className="textarea"
              value={note}
              onChange={(e) => setNote(e.target.value)}
              rows={2}
            />
          </div>
          <div className="row">
            <button
              type="button"
              className="btn btn-primary"
              disabled={!note.trim()}
              onClick={() => void resolveWithNote()}
            >
              Save note
            </button>
            <button type="button" className="btn btn-danger" onClick={() => void resolveWithTicket()}>
              Raise a ticket
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function stateLabel(s: DoorState): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ---------------------------------------------------------------- Location-Based Check

export function LocationCheckItem({ item, existing, checklistId, onSaved }: ItemProps) {
  const cfg = (item.config ?? {}) as unknown as LocationCheckConfig;
  const existingResult = existing?.result as
    | Extract<ItemResult, { type: "location_check" }>
    | undefined;
  const navigate = useNavigate();
  const location = useLocation();
  const current = useCurrent();

  const { data: nestedData } = db.useQuery(
    existingResult
      ? { checklists: { $: { where: { id: existingResult.nestedChecklistId } } } }
      : null,
  );
  const { data: locationData } = db.useQuery(
    !existingResult ? { locations: { $: { where: { id: cfg.locationId } } } } : null,
  );
  const nested = nestedData?.checklists?.[0];
  const locationName = locationData?.locations?.[0]?.name;
  const nestedComplete = nested?.status === "complete";

  const open = async () => {
    let nestedId = existingResult?.nestedChecklistId;
    if (!nestedId) {
      nestedId = deterministicId(`location-check:${checklistId}:${item.id}`);
      await db.transact([
        db.tx.checklists[nestedId]
          .update({
            status: "not_started",
            triggeredBy: {
              type: "location_check",
              parentChecklistId: checklistId,
              locationId: cfg.locationId,
            },
          })
          .link({ template: cfg.templateId, ...(current.user ? { assignedTo: current.user.id } : {}) }),
        db.tx.checklistItemResults[existing?.id ?? id()]
          .update({ result: { type: "location_check", nestedChecklistId: nestedId } })
          .link({ checklist: checklistId, templateItem: item.id }),
      ]);
      onSaved({ type: "location_check", nestedChecklistId: nestedId });
    }
    navigate(`/checklists/${nestedId}`, { state: { returnTo: location.pathname } });
  };

  return (
    <div className={"card" + (nestedComplete ? " card-done" : "")}>
      <div className="badge">Location-Based Check</div>
      <div className="card-title">{item.label}</div>
      <div className="card-meta">
        {locationName ? `Scoped to ${locationName}` : "Opens a nested sub-checklist"}
      </div>
      <div className="row" style={{ marginTop: 10 }}>
        <button type="button" className="btn" onClick={() => void open()}>
          {existingResult ? (nestedComplete ? "View nested checklist" : "Resume nested checklist") : "Open nested checklist"}
        </button>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------- Meter Reading

export function MeterReadingItem({ item, existing, checklistId, onSaved }: ItemProps) {
  const cfg = (item.config ?? {}) as unknown as MeterReadingConfig;
  const existingResult = existing?.result as
    | Extract<ItemResult, { type: "meter_reading" }>
    | undefined;
  const [assetId, setAssetId] = useState(cfg.assetId ?? "");
  const [value, setValue] = useState("");
  const [correctionReason, setCorrectionReason] = useState("");

  const { data } = db.useQuery(
    cfg.assetId
      ? { assets: { $: { where: { id: cfg.assetId } } } }
      : { assets: { $: { where: { hasMeter: true } } } },
  );
  const options = cfg.assetId ? [] : data?.assets ?? [];
  const asset = cfg.assetId ? data?.assets?.[0] : options.find((a) => a.id === assetId);

  const done = existingResult != null;
  const needsCorrection =
    asset?.meterReading != null && Number(value) < asset.meterReading && value !== "";

  const record = async () => {
    if (!asset) return;
    const numeric = Number(value);
    const readingId = id();
    const { data: fresh } = await db.queryOnce({
      assetMeterReadings: { $: { where: { "asset.id": asset.id } } },
      tickets: { $: { where: { "asset.id": asset.id } } },
    });
    const dueRules = dueMeterMaintenanceRules(
      asset,
      numeric,
      fresh?.assetMeterReadings ?? [],
      fresh?.tickets ?? [],
    );
    const ticketTxns = dueRules.map((rule) =>
      db.tx.tickets[id()]
        .update({
          title: maintenanceRuleTitle(asset, rule),
          priority: "medium",
          status: "open",
          autoGenerated: true,
          createdAt: Date.now(),
        })
        .link({ asset: asset.id }),
    );
    await db.transact([
      db.tx.assetMeterReadings[readingId]
        .update({
          value: numeric,
          source: "checklist_item",
          timestamp: Date.now(),
          ...(needsCorrection ? { correctionReason } : {}),
        })
        .link({ asset: asset.id }),
      db.tx.assets[asset.id].update({ meterReading: numeric }),
      ...ticketTxns,
    ]);
    const result: ItemResult = {
      type: "meter_reading",
      assetId: asset.id,
      value: numeric,
      meterReadingId: readingId,
    };
    await saveResult(checklistId, item.id, existing?.id, result);
    onSaved(result);
  };

  if (done) {
    return (
      <div className="card card-done">
        <div className="badge">Meter Reading</div>
        <div className="card-title">{item.label}</div>
        <div className="card-meta">Recorded {existingResult.value}</div>
      </div>
    );
  }

  return (
    <div className="card">
      <div className="badge">Meter Reading</div>
      <div className="card-title">{item.label}</div>

      {!cfg.assetId && (
        <div className="field">
          <span className="field-label">Asset</span>
          <select className="select" value={assetId} onChange={(e) => setAssetId(e.target.value)}>
            <option value="">Select…</option>
            {options.map((a) => (
              <option key={a.id} value={a.id}>
                {a.name}
              </option>
            ))}
          </select>
        </div>
      )}
      <div className="field">
        <span className="field-label">
          Reading{asset?.meterReading != null ? ` (current: ${asset.meterReading})` : ""}
        </span>
        <input
          className="input"
          type="number"
          value={value}
          onChange={(e) => setValue(e.target.value)}
        />
      </div>
      {needsCorrection && (
        <div className="field">
          <span className="field-label">
            Correction reason — required (reading is lower than the last one)
          </span>
          <textarea
            className="textarea"
            value={correctionReason}
            onChange={(e) => setCorrectionReason(e.target.value)}
            rows={2}
          />
        </div>
      )}
      <div className="row" style={{ marginTop: 8 }}>
        <button
          type="button"
          className="btn btn-primary"
          disabled={!asset || value === "" || (needsCorrection && !correctionReason.trim())}
          onClick={() => void record()}
        >
          Record reading
        </button>
      </div>
    </div>
  );
}
