#!/usr/bin/env bash
#
# Finish the PowerSync cutover — the steps that need a human in a dashboard.
#
# The rewrite is done and verified as far as it can be from here: it compiles,
# boots, and opens its own SQLite database. What it cannot do is sync, because
# PowerSync rejects every token this Clerk application currently issues. That
# is one checkbox in one dashboard, and it is stage 1.
#
# Everything in here is something an agent genuinely cannot do: a third-party
# dashboard, a deploy-time secret, or a decision about a marina's real data.
# Run it, then hand the outcome back.
#
#   bash scripts/finish-powersync-cutover.sh
#
# One-off. Delete it once beta is on Supabase.
#
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE=".env.local"

banner "Finish the PowerSync cutover"

# ── 1 ──────────────────────────────────────────────────────────────────
stage "Clerk — the claim that unblocks everything"
warn "Nothing syncs until this is done. Not less data — none."
say ""
say "PowerSync requires an \"aud\" claim on every token and rejects the ones"
say "without it (PSYNC_S2105). Clerk's session token carries none by default."
say "Supabase accepts the token either way, verified against a real minted JWT,"
say "so adding the claim costs nothing and one token keeps serving both."
open_url "https://dashboard.clerk.com/"
step "Pick THIS marina's Clerk application."
note "  present-penguin-25.clerk.accounts.dev"
step "Configure → Sessions → Customize session token → Edit."
step "Add this claim to the JSON, alongside whatever is already there:"
say  ""
say  '      "aud": "authenticated"'
say  ""
step "Save."
note "Reference: https://clerk.com/docs/guides/sessions/customize-session-tokens"
note "\"authenticated\" rather than something PowerSync-specific because it is"
note "also what a native Supabase token carries — the same token then reads"
note "correctly to anything that inspects it."
pause "Saved?"

# ── 2 ──────────────────────────────────────────────────────────────────
stage "Prove it landed"
say "Minting a real session token and reading its claims — the only way to"
say "know, rather than assume, that the dashboard change took effect."
say ""
if node scripts/check-clerk-claims.mjs; then
  say ""
  say "Every claim the stack needs is present."
else
  warn "A claim the stack needs is still missing — see above."
  warn "Go back to stage 1 before continuing; the rest of this is downstream."
  SKIPPED+=("the Clerk session token is still missing a claim — re-run stage 1")
fi
pause "Continue?"

# ── 3 ──────────────────────────────────────────────────────────────────
stage "Supabase — push the four new migrations"
say "The remote database is four migrations behind. They are the ones the"
say "rewrite depends on, and none of them can be applied later:"
say ""
step "003200  a real id on the 16 tables that had none — without it nothing"
note "        can be written to them, only read"
step "003300  claim_marina_user(), which is how anyone signs in for the"
note "        first time"
step "003400  one convention for activity_log_entries.subject_type"
step "003500  a template item outlives its section, so deleting a template"
note "        stops being refused"
say ""
note "The remote database has the schema and no rows, so this is close to"
note "risk-free today. It stops being risk-free the moment it has data."
if confirm "Run supabase db push against the linked project?"; then
  if supabase db push; then
    say ""
    say "Applied."
  else
    warn "Push failed — see above. The app cannot work against this database"
    warn "until the migrations land."
    SKIPPED+=("supabase db push — four migrations still not on the remote")
  fi
else
  SKIPPED+=("supabase db push — four migrations still not on the remote")
fi
pause "Continue?"

# ── 4 ──────────────────────────────────────────────────────────────────
stage "PowerSync — trust Clerk's keys, and accept that audience"
say "Two settings, both on the same screen, and the instance rejects every"
say "token until BOTH are right. The local service has both — they live in"
say "powersync/config/service.yaml as jwks_uri and audience — and an earlier"
say "version of this wizard asked for only the second. That omission is what"
say "PSYNC_S2204 \"JWKS request failed\" means: the instance is fetching a"
say "JWKS from somewhere that isn't Clerk, so it can never verify a signature."
say ""
say "The JWKS URI is Clerk's, NOT Supabase's. Supabase and PowerSync both"
say "trust the same Clerk token, so both point at the same Clerk endpoint."
say ""
JWKS="https://${CLERK_DOMAIN:-$(_existing CLERK_DOMAIN)}/.well-known/jwks.json"
say "For this marina that is:"
printf '  %s%s%s\n' "$BOLD" "$JWKS" "$RESET"
if curl -fsS -o /dev/null --max-time 10 "$JWKS" 2>/dev/null; then
  printf '  %s✓%s reachable and serving keys right now\n' "$GREEN" "$RESET"
else
  warn "that URL is not answering — check CLERK_DOMAIN in $ENV_FILE first"
fi
say ""
open_url "https://powersync.journeyapps.com/"
step "Open this marina's instance → Client Auth."
step "JWKS URI: paste the URL above."
step "Audience: authenticated"
step "Leave any \"use Supabase auth\" option OFF — these are Clerk tokens."
step "Save, then Deploy — neither setting does anything until the instance"
note "  redeploys. Watch for the deploy to report healthy before testing."
pause "Deployed?"

# ── 5 ──────────────────────────────────────────────────────────────────
stage "Netlify — the three public values"
say "beta builds from Netlify, and the build needs the new stack's config."
say "All three are public by design: they ship in the browser bundle, and the"
say "anon key grants nothing on its own because RLS evaluates the Clerk JWT."
say ""
say "From .env.local, add these to the beta site:"
say ""
step "VITE_SUPABASE_URL"
step "VITE_SUPABASE_ANON_KEY"
step "VITE_POWERSYNC_URL"
say ""
warn "Never add CLERK_SECRET_KEY, POWERSYNC_DB_PASSWORD, or a Supabase"
warn "service_role key. The frontend build must not see any of them."
note "VITE_INSTANT_APP_ID can go once beta is on Supabase, not before —"
note "the current beta build still needs it."
note "netlify.toml's SECRETS_SCAN_OMIT_KEYS already names the three new ones."
open_url "https://app.netlify.com/"
step "Site settings → Environment variables → Add a variable, three times."
pause "Added?"

# ── 6 ──────────────────────────────────────────────────────────────────
stage "Decide what the remote database holds"
say "PowerSync Cloud replicates from the REMOTE Postgres, not from your"
say "laptop — so beta shows an empty app until something is in there. The"
say "local stack already has the marina's real configuration plus a simulated"
say "year, which is what the rewrite has been developed against."
say ""
say "  1  Real configuration only — locations, checkpoints, templates, roles."
note "     Honest and empty. Fastest to trust, least useful to click around."
say "  2  Real configuration + the simulated year of occupancy."
note "     What local has. Realistic to use; the guests are invented."
say "  3  The real InstantDB export — every real guest and contact."
note "     Real contact details in a second live system. Say so deliberately."
say "  4  Not yet — leave it empty and decide later."
say ""
ask REMOTE_DATA_CHOICE "Which (1-4)?"
printf '%s\n' "$REMOTE_DATA_CHOICE" > /tmp/marina-remote-data-choice.txt
say ""
say "Recorded. Tell your agent which you picked — the loading itself is its"
say "job, and option 3 in particular needs deciding out loud before it runs."

finish
say "Next: with stages 1-3 done, the LOCAL stack is the honest place to see"
say "the rewrite work against real rows —"
note "  supabase start && pnpm run ps:up && pnpm run seed && pnpm run dev"
say "The local database has the seeded year; the remote has whatever you just"
say "chose in stage 6."
say ""
