#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# This repo's per-marina config lives in .env.local (gitignored via *.local),
# not .env — see .env.example.
ENV_FILE=".env.local"

banner "MarinaSecure — provision Supabase + PowerSync + Clerk"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Supabase — create this marina's project"
say "Every marina gets its own Supabase project. Nothing is shared."
note "docs/architecture.md — Per-marina isolation"
open_url "https://supabase.com/dashboard/new"
step "Create a new project. Name it after the marina."
step "Choose a region near the marina — sync latency is felt on the dock."
step "Save the database password somewhere safe. You need it in stage 5,"
say  "  and Supabase will not show it again."
warn "Free-tier projects pause after ~a week of inactivity."
pause "Project created and finished provisioning?"

step "Now open Project Settings → API (newer projects: 'API Keys')."
open_url "https://supabase.com/dashboard/project/_/settings/api"
step "Copy the Project URL (https://<ref>.supabase.co)."
ask VITE_SUPABASE_URL "Paste the Project URL:"
# The dashboard shows this several ways and the API docs render it with
# /rest/v1 appended. The Supabase client wants the bare project origin and
# adds the path itself, so normalise whatever was pasted.
VITE_SUPABASE_URL="${VITE_SUPABASE_URL%/}"
VITE_SUPABASE_URL="${VITE_SUPABASE_URL%/rest/v1}"
VITE_SUPABASE_URL="${VITE_SUPABASE_URL%/}"
step "Copy the anon / publishable key (NOT the service_role or secret key)."
note "This one is public by design — it ships in the browser bundle. It grants"
note "nothing on its own; RLS evaluates against the Clerk JWT."
ask VITE_SUPABASE_ANON_KEY "Paste the anon / publishable key:"
write_env VITE_SUPABASE_URL "$VITE_SUPABASE_URL"
write_env VITE_SUPABASE_ANON_KEY "$VITE_SUPABASE_ANON_KEY"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Clerk — activate the Supabase integration"
say "Clerk stays as the identity provider. Supabase is configured to trust it,"
say "so every RLS policy evaluates against a verified Clerk identity."
note "docs/adr/0005-supabase-and-powersync-replace-instantdb.md"
open_url "https://dashboard.clerk.com/"
step "Pick THIS marina's Clerk application (each marina has its own)."
step "Go to Configure → Integrations → Supabase, and click"
say  "  'Activate Supabase integration'."
step "It then shows your Clerk domain. Copy it."
note "Looks like: your-app-123.clerk.accounts.dev, or your custom domain."
note "Reference: https://clerk.com/docs/guides/development/integrations/databases/supabase"
ask CLERK_DOMAIN "Paste the Clerk domain (with or without https://):"
# Accept either form: a pasted scheme would otherwise build the stage 7 JWKS
# URL as "https://https://..." and silently fail verification.
CLERK_DOMAIN="${CLERK_DOMAIN#https://}"
CLERK_DOMAIN="${CLERK_DOMAIN#http://}"
CLERK_DOMAIN="${CLERK_DOMAIN%/}"
write_env CLERK_DOMAIN "$CLERK_DOMAIN"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Supabase — trust Clerk as a third-party auth provider"
warn "This is THE trap. Skip it and every policy evaluates against a null"
warn "identity, every query returns empty, and it looks exactly like an"
warn "unprovisioned account. CLAUDE.md records the Instant version of this"
warn "failure costing hours. Do not move on until it's saved."
open_url "https://supabase.com/dashboard/project/_/auth/third-party"
step "Authentication → Sign In / Providers → Add provider → Clerk."
step "Paste the Clerk domain from the previous stage:"
say  "    $CLERK_DOMAIN"
step "Save."
note "Reference: https://supabase.com/docs/guides/auth/third-party/clerk"
note "If you use a Clerk CUSTOM domain and verification later fails, check"
note "https://github.com/supabase/supabase/issues/44527 — some paths serve"
note "/.well-known/jwks rather than /.well-known/jwks.json."
pause "Clerk provider added and saved?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Supabase — create the PowerSync replication role"
say "PowerSync replicates from Postgres with its own least-privilege role,"
say "rather than a superuser or the service_role key."
if command -v openssl >/dev/null 2>&1; then
  POWERSYNC_DB_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-28)"
else
  POWERSYNC_DB_PASSWORD="$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | cut -c1-28)"
fi
write_env POWERSYNC_DB_PASSWORD "$POWERSYNC_DB_PASSWORD"
say ""
say "Run this in the Supabase SQL editor. It contains the generated password,"
say "so treat this screen as a secret:"
printf '\n%s' "$DIM"
cat <<SQL
    create role powersync_role
      with replication bypassrls login
      password '${POWERSYNC_DB_PASSWORD}';

    grant select on all tables in schema public to powersync_role;
    alter default privileges in schema public
      grant select on tables to powersync_role;

    create publication powersync for all tables;
SQL
printf '%s\n' "$RESET"
note "BYPASSRLS is required: the replication stream must see every row, and"
note "sync-stream scoping — not RLS — decides what reaches a device."
note "The publication MUST be named 'powersync'."
open_url "https://supabase.com/dashboard/project/_/sql/new"
pause "SQL run without errors?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Supabase — grab the database connection details"
say "PowerSync connects directly to Postgres, so it needs host/port/database"
say "plus the powersync_role credentials from the previous stage."
open_url "https://supabase.com/dashboard/project/_/settings/database"
step "Copy the connection host (db.<ref>.supabase.co) and port."
note "PowerSync needs a DIRECT connection, not the transaction pooler —"
note "logical replication doesn't work through PgBouncer in transaction mode."
warn "Supabase direct connections resolve to IPv6 ONLY unless the IPv4"
warn "add-on is enabled. With no IPv6 route, psql from your machine fails"
warn "with \'Network is unreachable\' — that does NOT mean the database is"
warn "broken, and PowerSync Cloud reaches it over IPv6 regardless."
note "If PowerSync\'s own connection test fails, switch to the Session pooler"
note "(username powersync_role.<project-ref>). The guide in the next stage"
note "covers which to pick."
ask SUPABASE_DB_HOST "Paste the database host:"
write_env SUPABASE_DB_HOST "$SUPABASE_DB_HOST"
say ""
say "You'll give PowerSync these in the next stage:"
say "    host      $SUPABASE_DB_HOST"
say "    database  postgres"
say "    username  powersync_role"
say "    password  (saved in $ENV_FILE as POWERSYNC_DB_PASSWORD)"
pause "Got the connection details?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "PowerSync — create the instance and connect it"
open_url "https://docs.powersync.com/integrations/supabase/guide"
say "That guide is the authority; the dashboard is here:"
open_url "https://powersync.journeyapps.com/"
step "Create a project for this marina, then create an instance."
step "Add a Postgres connection using the details from the previous stage."
step "Use the 'Test connection' button — do not skip it."
warn "If the connection test fails, stop and fix it here. A half-configured"
warn "instance fails later in ways that look like client bugs."
pause "Connection test passed?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "PowerSync — trust Clerk's JWKS"
say "PowerSync verifies the same Clerk token Supabase does, so a device can"
say "only sync as a real signed-in identity."
CLERK_JWKS_URL="https://${CLERK_DOMAIN}/.well-known/jwks.json"
write_env CLERK_JWKS_URL "$CLERK_JWKS_URL"
say ""
say "  JWKS URL:  $CLERK_JWKS_URL"
say ""
step "In the PowerSync dashboard, open your instance's Client Auth view."
step "Add the JWKS URL above as a custom / third-party auth source."
step "Save and Deploy."
note "Reference: https://docs.powersync.com/configuration/auth/custom"
note "Leave the audience blank unless PowerSync rejects tokens — Clerk's"
note "Supabase-integration tokens carry aud 'authenticated'."
pause "Client Auth saved and deployed?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "PowerSync — copy the instance URL"
step "On the instance overview, copy the instance URL."
note "Looks like: https://<id>.powersync.journeyapps.com"
ask VITE_POWERSYNC_URL "Paste the PowerSync instance URL:"
write_env VITE_POWERSYNC_URL "$VITE_POWERSYNC_URL"
say ""
say "Netlify serves the app, so the public values must exist there too."
open_url "https://app.netlify.com/"
step "Site settings → Environment variables. Add for the beta site:"
say  "    VITE_SUPABASE_URL"
say  "    VITE_SUPABASE_ANON_KEY"
say  "    VITE_POWERSYNC_URL"
note "All three are public by design. Never add a service_role key,"
note "POWERSYNC_DB_PASSWORD, or CLERK_SECRET_KEY to Netlify."
note "netlify.toml's SECRETS_SCAN_OMIT_KEYS will need the new VITE_ names,"
note "or the secrets scanner fails the build."
pause "Netlify variables added (or deferred)?"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Verify — prove each piece actually answers"
say "Anonymous probes only prove the easy half. These confirm the endpoints"
say "exist and are reachable; a real signed-in session is still the only"
say "thing that proves authorization works (CLAUDE.md)."
say ""

_check() {
  local label="$1" url="$2" expect="$3" code
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "$url" 2>/dev/null || echo "000")
  if [[ "$code" == "$expect" ]]; then
    printf '  %s✓%s %-28s HTTP %s\n' "$GREEN" "$RESET" "$label" "$code"
  else
    printf '  %s✗%s %-28s HTTP %s (expected %s)\n' "$RED" "$RESET" "$label" "$code" "$expect"
    SKIPPED+=("$label returned HTTP $code — re-check that stage")
  fi
}

_check "Clerk JWKS"        "$CLERK_JWKS_URL" "200"
# NOT the /rest/v1/ root: it serves the OpenAPI spec and now requires a
# SECRET key, so a publishable key always gets 401 there — a check that fails
# on a correctly provisioned project. Querying a table separates the two
# failures that matter: 401 means the key or URL is wrong; 404 (PGRST205,
# "table not found") means auth passed all the way to Postgres and the schema
# simply is not built yet, which is the expected state right now.
_sb=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 \
  -H "apikey: ${VITE_SUPABASE_ANON_KEY}" \
  "${VITE_SUPABASE_URL}/rest/v1/marina_settings?select=id&limit=1" 2>/dev/null || echo "000")
case "$_sb" in
  200|404|406)
    printf '  %s✓%s %-28s HTTP %s — key accepted, reached Postgres\n' "$GREEN" "$RESET" "Supabase REST" "$_sb" ;;
  401|403)
    printf '  %s✗%s %-28s HTTP %s — key or project URL is wrong\n' "$RED" "$RESET" "Supabase REST" "$_sb"
    SKIPPED+=("Supabase rejected the publishable key — re-check stage 1") ;;
  *)
    printf '  %s✗%s %-28s HTTP %s\n' "$RED" "$RESET" "Supabase REST" "$_sb"
    SKIPPED+=("Supabase REST returned HTTP $_sb — re-check stage 1") ;;
esac
# PowerSync's public health path isn't documented as stable, so this only
# asks whether the host answers at all — DNS, TLS, and a live instance.
_ps_code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "$VITE_POWERSYNC_URL" 2>/dev/null || echo "000")
if [[ "$_ps_code" == "000" ]]; then
  printf '  %s✗%s %-28s unreachable\n' "$RED" "$RESET" "PowerSync instance"
  SKIPPED+=("PowerSync instance URL did not respond — re-check stage 8")
else
  printf '  %s✓%s %-28s responded (HTTP %s)\n' "$GREEN" "$RESET" "PowerSync instance" "$_ps_code"
fi

say ""
if curl -s --max-time 15 "$CLERK_JWKS_URL" 2>/dev/null | grep -q '"keys"'; then
  printf '  %s✓%s Clerk JWKS contains a keys array\n' "$GREEN" "$RESET"
else
  printf '  %s✗%s Clerk JWKS has no keys array — PowerSync cannot verify tokens\n' "$RED" "$RESET"
  SKIPPED+=("Clerk JWKS did not return a keys array")
fi

say ""
warn "What these checks CANNOT prove: that Supabase actually trusts Clerk"
warn "(stage 3). Only a real signed-in token shows that. Once the schema"
warn "exists, verify deliberately — a Clerk JWT must come back 404/200, not"
warn "401 PGRST301. CLAUDE.md: anonymous probes prove only the easy half."
say ""
say "Next, from docs/TODO.md:"
note "  • Schema + policies — 42 tables per docs/data-model.md, RLS per its"
note "    tier column, effective_permissions view, pg_cron retention job"
note "  • Sync streams — always / occupancy / age, 30-day trailing window"
note "  • Transform + load — drop the one targetless ticket"
pause "Done?"

finish
