import { useQuery } from "@powersync/react";
import type { LockContext } from "@powersync/web";
import { db, stamp } from "../lib/db";
import { insert, update } from "./sql";
import type { Permission } from "../lib/permissions";

// The Activity Log — written at the moment of the change, never reconstructed.
//
// Entries are immutable and self-describing: `summary` is generated by the code
// that made the change, so an entry stays readable after its subject is edited
// beyond recognition, or deleted entirely. 27 entries in this marina's history
// already refer to checklist instances that no longer exist, and they still
// read correctly — that is the property, not a defect.

/**
 * The kind of thing an entry is about — a table name, checked by
 * activity_log_entries_subject_type_check.
 *
 * These were Instant namespace names until migration 003400; both conventions
 * were live in the same column at once. Table names win because they are the
 * only convention with an authority outside the client.
 */
export type SubjectType =
  | "assets"
  | "boats"
  | "calls"
  | "check_ins"
  | "checklist_instances"
  | "contacts"
  | "incidents"
  | "leases"
  | "locations"
  | "notes"
  | "reservations"
  | "roles"
  | "shifts"
  | "sms_threads"
  | "tickets"
  | "users"
  | "vehicles";

/**
 * Per-entry visibility: an entry shows only if the subject's own governing
 * permission is held. Subjects absent from this map are unrestricted —
 * tickets, locations, reservations, boats, assets, notes — matching how those
 * entities are treated everywhere else.
 */
const SUBJECT_PERMISSION: Partial<Record<SubjectType, Permission>> = {
  incidents: "view_incidents",
  contacts: "view_owner",
  leases: "view_lease",
  calls: "view_calls",
  sms_threads: "view_sms",
  users: "manage_users",
  roles: "manage_roles",
};

export function subjectPermission(subjectType: string): Permission | undefined {
  return SUBJECT_PERMISSION[subjectType as SubjectType];
}

export const SUBJECT_LABEL: Record<SubjectType, string> = {
  assets: "Asset",
  boats: "Boat",
  calls: "Call",
  check_ins: "Check-in",
  checklist_instances: "Checklist",
  contacts: "Contact",
  incidents: "Incident",
  leases: "Lease",
  locations: "Location",
  notes: "Note",
  reservations: "Reservation",
  roles: "Role",
  shifts: "Shift",
  sms_threads: "SMS thread",
  tickets: "Ticket",
  users: "User",
  vehicles: "Vehicle",
};

export function subjectLabel(subjectType: string): string {
  return SUBJECT_LABEL[subjectType as SubjectType] ?? "Record";
}

/** Route to a subject's own detail page, or null when it has none. */
export function subjectPath(
  subjectType: string,
  subjectId: string,
): string | null {
  switch (subjectType as SubjectType) {
    case "checklist_instances":
      return `/checklists/${subjectId}`;
    case "tickets":
      return `/tickets/${subjectId}`;
    case "incidents":
      return `/incidents/${subjectId}`;
    case "reservations":
      return `/reservations/${subjectId}`;
    case "locations":
      return `/locations/${subjectId}`;
    case "boats":
      return `/boats/${subjectId}`;
    case "vehicles":
      return `/vehicles/${subjectId}`;
    case "assets":
      return `/assets/${subjectId}`;
    case "contacts":
      return `/contacts/${subjectId}`;
    case "leases":
      return `/contacts/leases/${subjectId}`;
    default:
      // Check-ins, notes, shifts, users, roles, calls and SMS threads have no
      // standalone detail route of their own.
      return null;
  }
}

export interface ActivityInput {
  /** Dotted event name, e.g. "ticket.created". */
  eventType: string;
  /** Human-readable, generated at write time — never recomputed for display. */
  summary: string;
  subjectType: SubjectType;
  subjectId: string;
  /** Omit for system-generated events; the feed shows those as "System". */
  actorId?: string | null;
}

/**
 * Record an entry inside an open transaction, alongside the change it
 * describes.
 *
 * Same transaction, deliberately: PowerSync uploads a transaction's operations
 * together, so the change and its log entry cannot arrive separately — or, on a
 * device that goes flat between them, one without the other.
 */
export function recordActivity(
  tx: LockContext,
  input: ActivityInput,
): Promise<string> {
  return insert(tx, "activity_log_entries", {
    event_type: input.eventType,
    summary: input.summary,
    timestamp: stamp(),
    protected: 0,
    subject_type: input.subjectType,
    subject_id: input.subjectId,
    actor_id: input.actorId ?? null,
  });
}

/** Record an entry on its own, for call sites not already in a transaction. */
export function logActivity(input: ActivityInput): Promise<string> {
  return db.writeTransaction((tx) => recordActivity(tx, input));
}

export interface ActivityEntry {
  id: string;
  event_type: string;
  summary: string;
  timestamp: string;
  subject_type: string;
  subject_id: string;
  actor_id: string | null;
  actor_name: string | null;
  /** Survives the retention purge. Set by hand, never by the app. */
  protected: number;
}

/**
 * Mark an entry as surviving retention, or stop.
 *
 * The one write the client makes to the activity log, and the log never logs
 * it — an audit trail that records its own curation would be recursive noise.
 * Clients cannot delete entries at all; retention is a pg_cron job.
 */
export function setEntryProtected(
  entryId: string,
  isProtected: boolean,
): Promise<void> {
  return update(db, "activity_log_entries", entryId, {
    protected: isProtected ? 1 : 0,
  });
}

const FEED_SELECT = `
  SELECT a.id, a.event_type, a.summary, a.timestamp,
         a.subject_type, a.subject_id, a.actor_id, a.protected,
         u.name AS actor_name
    FROM activity_log_entries a
    LEFT JOIN users u ON u.id = a.actor_id`;

/** The whole feed, newest first. Filtering by permission is the caller's. */
export function useActivityFeed(limit = 300) {
  return useQuery<ActivityEntry>(
    `${FEED_SELECT} ORDER BY a.timestamp DESC LIMIT ?`,
    [limit],
  );
}

/** Entries about one record — the history strip on a detail page. */
export function useActivityFor(subjectType: string, subjectId: string | undefined) {
  return useQuery<ActivityEntry>(
    `${FEED_SELECT}
      WHERE a.subject_type = ? AND a.subject_id = ?
      ORDER BY a.timestamp DESC`,
    [subjectType, subjectId ?? ""],
  );
}

/**
 * Entries about any of several records — a location's own history plus its
 * checkpoints', say.
 *
 * The id list is interpolated as placeholders, not values: SQLite has no array
 * parameter, and building `IN (?, ?, ?)` is the only way to keep the ids
 * themselves bound.
 */
export function useActivityForMany(subjects: { type: string; id: string }[]) {
  const clause = subjects
    .map(() => "(a.subject_type = ? AND a.subject_id = ?)")
    .join(" OR ");
  return useQuery<ActivityEntry>(
    subjects.length
      ? `${FEED_SELECT} WHERE ${clause} ORDER BY a.timestamp DESC`
      : `${FEED_SELECT} WHERE 0`,
    subjects.flatMap((s) => [s.type, s.id]),
  );
}
