import { useQuery } from "@powersync/react";
import { db, stamp } from "../lib/db";
import { insert, transact, update } from "./sql";
import { recordActivity } from "./activity";
import {
  attachmentColumns,
  attachmentJoins,
  attachmentSelect,
  type AttachedRow,
  type AttachmentTarget,
} from "./attachments";

// Tickets — the marina's work queue.
//
// Deliberately ungated: every role sees the queue and can raise a ticket. Only
// taking and assigning are permission-checked, and only in the UI — a ticket is
// Tier 0 in RLS, so the database will accept an assignment from anyone. That is
// the documented split, not an oversight; see docs/permissions.md.

export interface TicketRow extends AttachedRow {
  id: string;
  title: string;
  description: string | null;
  priority: string;
  status_id: string;
  auto_generated: number;
  created_at: string;
  resolved_at: string | null;
  created_by_id: string | null;
  assigned_to_id: string | null;
  source_incident_id: string | null;
  source_checklist_item_id: string | null;
  status_name: string;
  status_is_terminal: number;
  assignee_name: string | null;
  creator_name: string | null;
  source_incident_title: string | null;
}

const TICKET_SELECT = `
  SELECT t.*,
         s.name AS status_name,
         s.is_terminal AS status_is_terminal,
         au.name AS assignee_name,
         cu.name AS creator_name,
         si.title AS source_incident_title,
         ${attachmentSelect("t")}
    FROM tickets t
    JOIN ticket_statuses s ON s.id = t.status_id
    LEFT JOIN users au ON au.id = t.assigned_to_id
    LEFT JOIN users cu ON cu.id = t.created_by_id
    LEFT JOIN incidents si ON si.id = t.source_incident_id
    ${attachmentJoins("t")}`;

/**
 * The queue, urgent first and newest within a priority.
 *
 * Priority is an enum whose declaration order is low→urgent, and SQLite has no
 * knowledge of that ordering — so it is spelled out here rather than sorted in
 * JavaScript after the fact, which would have to re-sort on every render.
 */
export function useTickets() {
  return useQuery<TicketRow>(
    `${TICKET_SELECT}
      ORDER BY CASE t.priority
                 WHEN 'urgent' THEN 0 WHEN 'high' THEN 1
                 WHEN 'medium' THEN 2 WHEN 'low' THEN 3 ELSE 4 END,
               t.created_at DESC`,
  );
}

export function useTicket(ticketId: string | undefined) {
  const { data, isLoading } = useQuery<TicketRow>(
    `${TICKET_SELECT} WHERE t.id = ?`,
    [ticketId ?? ""],
  );
  return { ticket: data[0] ?? null, isLoading };
}

/** Open tickets attached to one target — a location's or asset's own queue. */
export function useTicketsForTarget(
  column: "location_id" | "checkpoint_id" | "boat_id" | "vehicle_id" | "contact_id" | "asset_id",
  targetId: string | undefined,
) {
  return useQuery<TicketRow>(
    `${TICKET_SELECT} WHERE t.${column} = ? ORDER BY t.created_at DESC`,
    [targetId ?? ""],
  );
}

export interface NewTicket {
  title: string;
  description?: string;
  priority: string;
  target: AttachmentTarget;
  statusId: string;
  sourceIncidentId?: string | null;
  sourceChecklistItemId?: string | null;
  autoGenerated?: boolean;
}

export async function createTicket(
  input: NewTicket,
  actorId: string | null,
): Promise<string> {
  return transact(async (tx) => {
    const ticketId = await insert(tx, "tickets", {
      title: input.title,
      description: input.description || null,
      priority: input.priority,
      status_id: input.statusId,
      auto_generated: input.autoGenerated ? 1 : 0,
      created_at: stamp(),
      created_by_id: actorId,
      source_incident_id: input.sourceIncidentId ?? null,
      source_checklist_item_id: input.sourceChecklistItemId ?? null,
      ...attachmentColumns(input.target),
    });
    await recordActivity(tx, {
      eventType: "ticket.created",
      summary: `Ticket "${input.title}" created on ${input.target.label}`,
      subjectType: "tickets",
      subjectId: ticketId,
      actorId,
    });
    return ticketId;
  });
}

export async function assignTicket(
  ticket: { id: string; title: string },
  assignee: { id: string; name: string },
  actorId: string | null,
): Promise<void> {
  await transact(async (tx) => {
    await update(tx, "tickets", ticket.id, { assigned_to_id: assignee.id });
    await recordActivity(tx, {
      eventType: "ticket.assigned",
      summary: `"${ticket.title}" assigned to ${assignee.name}`,
      subjectType: "tickets",
      subjectId: ticket.id,
      actorId,
    });
  });
}

export async function setTicketStatus(
  ticket: { id: string; title: string },
  status: { id: string; name: string; is_terminal: number },
  actorId: string | null,
): Promise<void> {
  await transact(async (tx) => {
    await update(tx, "tickets", ticket.id, {
      status_id: status.id,
      // resolved_at tracks the terminal status, and is cleared if the ticket
      // reopens — the maintenance-rule baseline reads it, so a stale value
      // suppresses the next rule firing rather than merely looking wrong.
      resolved_at: status.is_terminal === 1 ? stamp() : null,
    });
    await recordActivity(tx, {
      eventType: "ticket.status_changed",
      summary: `"${ticket.title}" set to ${status.name}`,
      subjectType: "tickets",
      subjectId: ticket.id,
      actorId,
    });
  });
}

export async function setTicketPriority(
  ticket: { id: string; title: string },
  priority: string,
  label: string,
  actorId: string | null,
): Promise<void> {
  await transact(async (tx) => {
    await update(tx, "tickets", ticket.id, { priority });
    await recordActivity(tx, {
      eventType: "ticket.priority_changed",
      summary: `"${ticket.title}" priority set to ${label}`,
      subjectType: "tickets",
      subjectId: ticket.id,
      actorId,
    });
  });
}

/** Open auto-generated tickets for an asset, for the maintenance-rule check. */
export function ticketsForAsset(assetId: string): Promise<TicketRow[]> {
  return db.getAll<TicketRow>(
    `${TICKET_SELECT} WHERE t.asset_id = ? AND t.auto_generated = 1`,
    [assetId],
  );
}
